package metadata

var Exports = []string{
	"IMetadataDictionary",
	"MetadataAlias",
	"MetadataAliasType",
	"MetadataApplication",
	"MetadataArray",
	"MetadataArrayType",
	"MetadataAtomic",
	"MetadataComponents",
	"MetadataConstant",
	"MetadataConstantValue",
	"MetadataEscaped",
	"MetadataFunction",
	"MetadataMap",
	"MetadataNative",
	"MetadataObject",
	"MetadataObjectType",
	"MetadataParameter",
	"MetadataProperty",
	"MetadataSchema",
	"MetadataSet",
	"MetadataCollection",
	"MetadataTemplate",
	"MetadataTuple",
	"MetadataTupleType",
}
