import { TestValidator } from "@nestia/e2e";
import { OpenApiConverter } from "@typia/utils";
import typia, { tags } from "typia";

/**
 * Verifies generated byte metadata crosses the OpenAPI 3.0/3.1 boundary.
 *
 * The native generator emits Typia's canonical `format: "byte"` metadata.
 * OpenAPI 3.0 keeps that spelling, whereas a raw OpenAPI 3.1 Schema Object
 * produced by the converter uses `contentEncoding: "base64"` and retains an
 * explicitly declared content media type.
 *
 * 1. Generate canonical byte metadata for OpenAPI 3.0 and emended 3.1 schemas.
 * 2. Downgrade generated schemas to raw 3.1 and verify encoding/media annotations.
 * 3. Upgrade legacy output and cross the boundary again without changing byte
 *    semantics.
 */
export const test_json_schema_byte_content_encoding = (): void => {
  const legacy = typia.json.schema<Pick<IBytePayload, "data">, "3.0">();
  const emended = typia.json.schema<IBytePayload, "3.1">();

  TestValidator.equals("generated 3.0", clean(legacy.schema), {
    type: "object",
    properties: {
      data: { type: "string", format: "byte" },
    },
    required: ["data"],
    additionalProperties: false,
  });
  TestValidator.equals("generated emended 3.1", clean(emended.schema), {
    type: "object",
    properties: {
      data: { type: "string", format: "byte" },
      image: {
        type: "string",
        format: "byte",
        contentMediaType: "image/png",
      },
    },
    required: ["data", "image"],
    additionalProperties: false,
  });

  TestValidator.equals(
    "generated raw 3.1",
    clean(
      OpenApiConverter.downgradeSchema({
        components: emended.components,
        downgraded: {},
        schema: emended.schema,
        version: "3.1",
      }),
    ),
    {
      type: "object",
      properties: {
        data: { type: "string", contentEncoding: "base64" },
        image: {
          type: "string",
          contentEncoding: "base64",
          contentMediaType: "image/png",
        },
      },
      required: ["data", "image"],
      additionalProperties: false,
    },
  );
  TestValidator.equals(
    "generated 3.0 upgraded then downgraded to 3.1",
    clean(
      OpenApiConverter.downgradeSchema({
        components: OpenApiConverter.upgradeComponents(legacy.components),
        downgraded: {},
        schema: OpenApiConverter.upgradeSchema({
          components: legacy.components,
          schema: legacy.schema,
        }),
        version: "3.1",
      }),
    ),
    {
      type: "object",
      properties: {
        data: { type: "string", contentEncoding: "base64" },
      },
      required: ["data"],
      additionalProperties: false,
    },
  );
};

interface IBytePayload {
  data: string & tags.Format<"byte">;
  image: string & tags.Format<"byte"> & tags.ContentMediaType<"image/png">;
}

const clean = <T>(value: T): T => JSON.parse(JSON.stringify(value));
