import { TestEquality } from "@typia/template/equality";
import { OpenApiConverter } from "@typia/utils";
import typia, { tags } from "typia";

/**
 * Verifies generated byte metadata crosses the OpenAPI 3.0/3.1 boundary.
 *
 * The native generator emits Typia's canonical `format: "byte"` metadata.
 * OpenAPI 3.0 keeps that spelling, whereas a raw OpenAPI 3.1 Schema Object
 * produced by the converter uses `contentEncoding: "base64"` and retains an
 * explicitly declared content media type.
 *
 * @evidence contracts/testing.md#behavioral-verification The actual exported case asserts that generated 3.0 and emended 3.1 byte schemas survive public upgrade/downgrade conversion with media type intact.
 * @evidence contracts/testing.md#independent-expectations Authored expected objects distinguish canonical format:byte from raw 3.1 contentEncoding:base64; contentMediaType comes from the declared image tag.
 * @evidence contracts/testing.md#distinguishing-cases Legacy/emended/raw schemas and legacy-to-raw conversion retain the same byte payload meaning; media type has an adjacent untagged control.
 * @evidence contracts/testing.md#execution-ownership DynamicExecutor discovers test_json_schema_byte_content_encoding through test-typia-schema start. Its actual typia call expressions are transformed in the suite project and their emitted values are evaluated in the existing runner.
 * @evidence contracts/e2e.md#necessary-boundary Native tag emission must supply the converter with the canonical byte metadata it consumes. Direct schema-writer unit calls do not establish TypeScript call resolution, emitted JavaScript evaluation and public runtime consumption together.
 * @evidence contracts/e2e.md#shared-execution The case uses the existing ttsx schema-suite project and runner; sibling schema cases reuse the same content-keyed plugin artifact. All declared variants are prepared together, without per-variant compiler launches or fixture installs.
 * @evidence contracts/e2e.md#state-isolation-and-reuse-validity Produced schema objects and helper projections belong to this invocation; no generated schema is retained between cases. The suite owns process termination and ttsc owns content-keyed artifact invalidation; this case makes no cold-cache assertion.
 * @evidence contracts/e2e.md#preserved-coverage Legacy/emended/raw schemas and legacy-to-raw conversion retain the same byte payload meaning; media type has an adjacent untagged control. Every original producer call and assertion stays enrolled under the same exported case; no portable assertion was removed or represented as independently covered elsewhere.
 */
export const test_json_schema_byte_content_encoding = (): void => {
  const legacy = typia.json.schema<Pick<IBytePayload, "data">, "3.0">();
  const emended = typia.json.schema<IBytePayload, "3.1">();

  TestEquality.equals("generated 3.0", clean(legacy.schema), {
    type: "object",
    properties: {
      data: { type: "string", format: "byte" },
    },
    required: ["data"],
    additionalProperties: false,
  });
  TestEquality.equals("generated emended 3.1", clean(emended.schema), {
    type: "object",
    properties: {
      data: { type: "string", format: "byte" },
      image: {
        type: "string",
        format: "byte",
        contentMediaType: "image/png",
      },
    },
    required: ["data", "image"],
    additionalProperties: false,
  });

  TestEquality.equals(
    "generated raw 3.1",
    clean(
      OpenApiConverter.downgradeSchema({
        components: emended.components,
        downgraded: {},
        schema: emended.schema,
        version: "3.1",
      }),
    ),
    {
      type: "object",
      properties: {
        data: { type: "string", contentEncoding: "base64" },
        image: {
          type: "string",
          contentEncoding: "base64",
          contentMediaType: "image/png",
        },
      },
      required: ["data", "image"],
      additionalProperties: false,
    },
  );
  TestEquality.equals(
    "generated 3.0 upgraded then downgraded to 3.1",
    clean(
      OpenApiConverter.downgradeSchema({
        components: OpenApiConverter.upgradeComponents(legacy.components),
        downgraded: {},
        schema: OpenApiConverter.upgradeSchema({
          components: legacy.components,
          schema: legacy.schema,
        }),
        version: "3.1",
      }),
    ),
    {
      type: "object",
      properties: {
        data: { type: "string", contentEncoding: "base64" },
      },
      required: ["data"],
      additionalProperties: false,
    },
  );
};

interface IBytePayload {
  data: string & tags.Format<"byte">;
  image: string & tags.Format<"byte"> & tags.ContentMediaType<"image/png">;
}

const clean = <T>(value: T): T => JSON.parse(JSON.stringify(value));
