import { TestEquality } from "@typia/template/equality";
import { OpenApiConverter } from "@typia/utils";
import typia, { tags } from "typia";

/**
 * Verifies generated byte metadata crosses the OpenAPI 3.0/3.1 boundary.
 *
 * The native generator emits Typia's canonical `format: "byte"` metadata.
 * OpenAPI 3.0 keeps that spelling, whereas a raw OpenAPI 3.1 Schema Object
 * produced by the converter uses `contentEncoding: "base64"` and retains an
 * explicitly declared content media type.
 *
 * @evidence contracts/testing.md#behavioral-verification typia.json.schema is evaluated by the native host on the types declared in this case and the result is checked by 4 assertions (generated 3.0; generated emended 3.1; generated raw 3.1; generated 3.0 upgraded then downgraded to 3.1). The case documents its purpose as: Verifies generated byte metadata crosses the OpenAPI 3.0/3.1 boundary.
 * @evidence contracts/testing.md#independent-expectations The case states its expectation basis: The native generator emits Typia's canonical `format: "byte"` metadata. OpenAPI 3.0 keeps that spelling, whereas a raw OpenAPI 3.1 Schema Object produced by the converter uses `contentEncoding: "base64"` and retains an explicitly declared content media type. Properties of the generated value that are not asserted are not certified.
 * @evidence contracts/testing.md#distinguishing-cases The assertion titles (generated 3.0; generated emended 3.1; generated raw 3.1; generated 3.0 upgraded then downgraded to 3.1) are the distinctions this case owns. Twins that are not named by those titles are either owned by sibling cases in this workspace or not asserted.
 * @evidence contracts/testing.md#execution-ownership The test-typia-schema start command (DynamicExecutor over src/features under ttsx with the native typia plugin) discovers this case: test_json_schema_byte_content_encoding is the exported entry; the native producer is a real boundary here because the typia calls are rewritten by the native host.
 */
export const test_json_schema_byte_content_encoding = (): void => {
  const legacy = typia.json.schema<Pick<IBytePayload, "data">, "3.0">();
  const emended = typia.json.schema<IBytePayload, "3.1">();

  TestEquality.equals("generated 3.0", clean(legacy.schema), {
    type: "object",
    properties: {
      data: { type: "string", format: "byte" },
    },
    required: ["data"],
    additionalProperties: false,
  });
  TestEquality.equals("generated emended 3.1", clean(emended.schema), {
    type: "object",
    properties: {
      data: { type: "string", format: "byte" },
      image: {
        type: "string",
        format: "byte",
        contentMediaType: "image/png",
      },
    },
    required: ["data", "image"],
    additionalProperties: false,
  });

  TestEquality.equals(
    "generated raw 3.1",
    clean(
      OpenApiConverter.downgradeSchema({
        components: emended.components,
        downgraded: {},
        schema: emended.schema,
        version: "3.1",
      }),
    ),
    {
      type: "object",
      properties: {
        data: { type: "string", contentEncoding: "base64" },
        image: {
          type: "string",
          contentEncoding: "base64",
          contentMediaType: "image/png",
        },
      },
      required: ["data", "image"],
      additionalProperties: false,
    },
  );
  TestEquality.equals(
    "generated 3.0 upgraded then downgraded to 3.1",
    clean(
      OpenApiConverter.downgradeSchema({
        components: OpenApiConverter.upgradeComponents(legacy.components),
        downgraded: {},
        schema: OpenApiConverter.upgradeSchema({
          components: legacy.components,
          schema: legacy.schema,
        }),
        version: "3.1",
      }),
    ),
    {
      type: "object",
      properties: {
        data: { type: "string", contentEncoding: "base64" },
      },
      required: ["data"],
      additionalProperties: false,
    },
  );
};

interface IBytePayload {
  data: string & tags.Format<"byte">;
  image: string & tags.Format<"byte"> & tags.ContentMediaType<"image/png">;
}

const clean = <T>(value: T): T => JSON.parse(JSON.stringify(value));
