packages:
  - 'internals/*'
  - 'packages/*'
  - 'tests/*'
catalogs:
  typescript:
    '@types/ts-expose-internals': npm:ts-expose-internals@5.6.3
    ts-node: ^10.9.2
    ts-patch: ^3.3.0
    typescript: ~5.9.3
  rollup:
    rollup: ^4.56.0
    rollup-plugin-auto-external: ^2.0.0
    rollup-plugin-node-externals: ^8.1.2
    '@rollup/plugin-commonjs': ^29.0.0
    '@rollup/plugin-node-resolve': ^16.0.3
    '@rollup/plugin-terser': ^0.4.4
    '@rollup/plugin-typescript': ^12.3.0
  utils:
    '@nestia/e2e': ^10.0.2
<<<<<<< HEAD
    '@types/node': ^25.0.10
=======
    '@types/node': ^25.3.0
>>>>>>> a7cbc4f1aec621fbd409afc8da295570e4fa2713
    '@types/uuid': ^11.0.0
    openai: ^6.16.0
    rimraf: ^6.1.2
    uuid: ^13.0.0
    tstl: ^3.0.0
<<<<<<< HEAD
    tgrid: ^1.2.1
  unplugin:
    '@rollup/pluginutils': ^5.1.4
    consola: ^3.4.2
    defu: ^6.1.4
    diff-match-patch-es: ^1.0.1
    find-cache-dir: ^5.0.0
    magic-string: ^0.30.17
    pathe: ^2.0.3
    pkg-types: ^2.1.0
    type-fest: ^4.37.0
    unplugin: ^2.2.2
    tsdown: ^0.12.7
    vite: ^6.2.2
    vitest: ^3.0.9
    esbuild: ^0.25.5
    rollup-plugin-esbuild: ^6.2.1
=======
    tgrid: ^1.2.1
>>>>>>> a7cbc4f1aec621fbd409afc8da295570e4fa2713
