import { IHttpLlmApplication, ILlmApplication } from "@typia/interface";
import { HttpLlm, OpenApiConverter } from "@typia/utils";
import fs from "fs";
import { Singleton } from "tstl";
import typia from "typia";

import { TestGlobal } from "../../../TestGlobal";

/**
 * Verifies an HTTP LLM application conforms to the ILlmApplication type.
 *
 * An HttpLlm application must be usable wherever an ILlmApplication is
 * expected. Validating it with a native typia.assert of the interface catches
 * structural drift between the two declarations.
 *
 * 1. Compose an application from the checked-in shopping example.
 * 2. Assert it with the natively generated ILlmApplication validator.
 *
 * @evidence contracts/testing.md#behavioral-verification HttpLlm.application runs on a real document and the result is checked by the validator typia generates for ILlmApplication; a missing or mistyped member throws.
 * @evidence contracts/testing.md#independent-expectations The ILlmApplication declaration in @typia/interface is the specification and the native assertion is generated from it, independently of the composer.
 * @evidence contracts/testing.md#distinguishing-cases One real document and one validator; it does not distinguish which member drifted beyond the thrown validation error.
 * @evidence contracts/testing.md#execution-ownership The test-utils test:integration command (DynamicExecutor over src/features under ttsx with the native typia plugin) discovers this exported case. typia.assert is generated by the native transform, so a native producer is required, and the example document is read from disk.
 * @evidence contracts/e2e.md#necessary-boundary The shopping document flows through upgradeDocument and HttpLlm.application into a native application-type assert. This establishes structural assembly against the declaration, not endpoint semantic equivalence.
 * @evidence contracts/e2e.md#shared-execution This case shares the test-utils integration project and native-plugin artifact lifecycle with the other src/features exports. Its runtime rows reuse emitted schemas/callbacks in this invocation instead of starting a compiler host per input; it performs no independent installation or host launch.
 * @evidence contracts/e2e.md#state-isolation-and-reuse-validity Each invocation owns its schema/definition objects and payloads; document callers parse fresh text before conversion. Compiler-artifact reuse cannot supply a prior runtime verdict. This case opens no persistent service/process handle; fixture-reader unit temporary files are owned and released by that separate unit.
 * @evidence contracts/e2e.md#preserved-coverage The previous inputs, producer calls and behavioral assertions remain in this exported DynamicExecutor case; portable rows described above have not yet been transferred to unit coverage. Producer parity and structural acceptance retain their stated oracle limits rather than certifying semantic correctness.
 */
export const test_llm_application_type = (): void => {
  const http: IHttpLlmApplication = application();
  const classic: Omit<ILlmApplication, "config"> = http;
  typia.assert(classic);
};

const application = () =>
  HttpLlm.application({
    document: document.get(),
  });

const document = new Singleton(() =>
  OpenApiConverter.upgradeDocument(
    JSON.parse(
      fs.readFileSync(`${TestGlobal.ROOT}/examples/v3.1/shopping.json`, "utf8"),
    ),
  ),
);
