
// Code generated by packages/ttsc/tools/gen_shims. DO NOT EDIT.

package vfs

import "github.com/microsoft/typescript-go/internal/vfs"

type DirEntry = vfs.DirEntry
type Entries = vfs.Entries
var ErrClosed = vfs.ErrClosed
var ErrExist = vfs.ErrExist
var ErrInvalid = vfs.ErrInvalid
var ErrNotExist = vfs.ErrNotExist
var ErrPermission = vfs.ErrPermission
type FS = vfs.FS
type FileInfo = vfs.FileInfo
var SkipAll = vfs.SkipAll
var SkipDir = vfs.SkipDir
type WalkDirFunc = vfs.WalkDirFunc
