import { TestValidator } from "@nestia/e2e";
import { ILlmSchema, OpenApi } from "@typia/interface";
import { TestEquality } from "@typia/oracle/equality";
import { LlmSchemaConverter, OpenApiTypeChecker } from "@typia/utils";

/**
 * Verifies inversion translates discriminator references without losing
 * variants.
 *
 * Prefix-only checks permit an empty or misbound mapping. Exact independently
 * authored references distinguish both failures; native raw-union generation
 * remains in the existing schema specification boundary batch.
 *
 * 1. Invert a two-variant LLM schema and compare its references, discriminator and
 *    complete component field constraints.
 * 2. Remove only discriminator metadata and require the same variants without an
 *    invented discriminator.
 *
 * @evidence contracts/testing.md#behavioral-verification LlmSchemaConverter.invert must translate two LLM references and their discriminator mapping into OpenAPI component references while retaining cat and ant field constraints. The original invert predicate remains, with exact independent output comparisons.
 * @evidence contracts/testing.md#independent-expectations Authored LLM fixtures express the cat/ant type fields; literal expected OpenAPI references, mapping and components follow inversion's public preservation contract. They are neither generated by typia nor derived from the returned output.
 * @evidence contracts/testing.md#distinguishing-cases The positive case requires both mapping entries and every original cat/ant field, including ant's three role literals. Removing only discriminator metadata is the negative twin: both variants survive without synthesized discriminator metadata. Empty and wrong-target mappings cannot satisfy the exact positive comparison.
 * @evidence contracts/testing.md#execution-ownership The matching export is explicitly registered in test-utils test:unit plugin-free node:test runner and uses the direct oracle. A discriminator predicate over generated input executes in the native spec-union batch, where a raw union is actually generated; it is not an assertion on this authored fixture.
 */
export const test_llm_schema_discriminator = (): void => {
  const $defs: Record<string, ILlmSchema> = {
    ICat: {
      type: "object",
      properties: {
        type: { type: "string", enum: ["cat"] },
        name: { type: "string" },
        ribbon: { type: "boolean" },
      },
      required: ["type", "name", "ribbon"],
      additionalProperties: false,
    },
    IAnt: {
      type: "object",
      properties: {
        type: { type: "string", enum: ["ant"] },
        name: { type: "string" },
        role: { type: "string", enum: ["queen", "soldier", "worker"] },
      },
      required: ["type", "name", "role"],
      additionalProperties: false,
    },
  };
  const schema: ILlmSchema.IAnyOf = {
    anyOf: [{ $ref: "#/$defs/ICat" }, { $ref: "#/$defs/IAnt" }],
    "x-discriminator": {
      propertyName: "type",
      mapping: { cat: "#/$defs/ICat", ant: "#/$defs/IAnt" },
    },
  };
  const components: OpenApi.IComponents = {};
  const invert: OpenApi.IJsonSchema = LlmSchemaConverter.invert({
    components,
    $defs,
    schema,
  });
  TestValidator.predicate(
    "invert",
    () =>
      OpenApiTypeChecker.isOneOf(invert) &&
      invert.discriminator !== undefined &&
      invert.discriminator.mapping !== undefined &&
      Object.values(invert.discriminator.mapping).every((k) =>
        k.startsWith("#/components/schemas/"),
      ),
  );
  TestEquality.equals<unknown>(
    "exact discriminator and variants",
    {
      oneOf: [
        { $ref: "#/components/schemas/ICat" },
        { $ref: "#/components/schemas/IAnt" },
      ],
      discriminator: {
        propertyName: "type",
        mapping: {
          cat: "#/components/schemas/ICat",
          ant: "#/components/schemas/IAnt",
        },
      },
    },
    OpenApiTypeChecker.isOneOf(invert)
      ? { oneOf: invert.oneOf, discriminator: invert.discriminator }
      : invert,
  );
  TestEquality.equals<OpenApi.IComponents>(
    "complete variant fields",
    {
      schemas: {
        ICat: {
          type: "object",
          properties: {
            type: { const: "cat" },
            name: { type: "string" },
            ribbon: { type: "boolean" },
          },
          required: ["type", "name", "ribbon"],
          additionalProperties: false,
        },
        IAnt: {
          type: "object",
          properties: {
            type: { const: "ant" },
            name: { type: "string" },
            role: {
              oneOf: [
                { const: "queen" },
                { const: "soldier" },
                { const: "worker" },
              ],
            },
          },
          required: ["type", "name", "role"],
          additionalProperties: false,
        },
      },
    },
    components,
  );
  const plain = LlmSchemaConverter.invert({
    components: {},
    $defs,
    schema: { anyOf: [{ $ref: "#/$defs/ICat" }, { $ref: "#/$defs/IAnt" }] },
  });
  TestEquality.equals<OpenApi.IJsonSchema>(
    "plain union variants",
    {
      oneOf: [
        { $ref: "#/components/schemas/ICat" },
        { $ref: "#/components/schemas/IAnt" },
      ],
    },
    plain,
  );
  TestEquality.equals(
    "plain union has no discriminator",
    OpenApiTypeChecker.isOneOf(plain)
      ? plain.discriminator
      : "wrong schema kind",
    undefined,
  );
};
