import { IHttpMigrateApplication, OpenApi, SwaggerV2 } from "@typia/interface";
import { HttpMigration, OpenApiConverter } from "@typia/utils";
import fs from "fs";
import typia from "typia";

import { TestGlobal } from "../../TestGlobal";

/**
 * Verifies every Swagger 2.0 example document migrates to a valid application.
 *
 * Real documents exercise the whole migration pipeline; the result must satisfy
 * the IHttpMigrateApplication contract.
 *
 * 1. Read each v2.0 example, validate it with the native validator and upgrade it.
 * 2. Migrate it with HttpMigration.application.
 * 3. Assert the application with the native IHttpMigrateApplication validator.
 *
 * @evidence contracts/testing.md#behavioral-verification Each example is upgraded and migrated and the application is checked by a natively generated validator; a document that fails any step throws.
 * @evidence contracts/testing.md#independent-expectations The interface declaration is the specification; the validators are generated from it independently of the migrator.
 * @evidence contracts/testing.md#distinguishing-cases Every example file is a case, with no per-file expectation beyond structural validity.
 * @evidence contracts/testing.md#execution-ownership The test-utils test:integration command (DynamicExecutor over src/features under ttsx with the native typia plugin) discovers this exported case. typia.assert validators are generated by the native transform and the examples are read from disk.
 */
export const test_http_migrate_v20 = async (): Promise<void> => {
  const path: string = `${TestGlobal.ROOT}/examples/v2.0`;
  for (const file of await fs.promises.readdir(path)) {
    if (file.endsWith(".json") === false) continue;
    const swagger: SwaggerV2.IDocument = typia.assert<SwaggerV2.IDocument>(
      JSON.parse(await fs.promises.readFile(`${path}/${file}`, "utf8")),
    );
    const openapi: OpenApi.IDocument =
      OpenApiConverter.upgradeDocument(swagger);
    const migrate: IHttpMigrateApplication = HttpMigration.application(openapi);
    typia.assert(migrate);
  }
};
