import {
  IHttpMigrateApplication,
  OpenApi,
  OpenApiV3_2,
} from "@typia/interface";
import { HttpMigration, OpenApiConverter } from "@typia/utils";
import fs from "fs";
import typia from "typia";

import { TestGlobal } from "../../TestGlobal";
import { _readJsonFixturePaths } from "../../internal/_readJsonFixturePaths";

/**
 * Verifies every OpenAPI 3.2 example migrates and its query routes are kept.
 *
 * 3.2 adds the query method; the migrated application must hold one query route
 * per query operation.
 *
 * 1. Read each v3.2 example and validate it natively.
 * 2. Upgrade and migrate it and validate the application.
 * 3. Count query routes against the query operations of the source.
 *
 * @evidence contracts/testing.md#behavioral-verification Each example is migrated, validated natively and its query route count is compared with the source's query operations.
 * @evidence contracts/testing.md#independent-expectations The expected count is computed from the source document's own paths, not from the migrator.
 * @evidence contracts/testing.md#distinguishing-cases Documents with and without query operations are covered only to the extent the checked-in examples contain them.
 * @evidence contracts/testing.md#execution-ownership The test-utils test:integration command (DynamicExecutor over src/features under ttsx with the native typia plugin) discovers this exported case. typia.assert validators are generated by the native transform and the examples are read from disk.
 * @evidence contracts/e2e.md#necessary-boundary Checked-in 3.2 documents pass through native input guards, migration conversion and native output guards for the 3.2 contract. The shared reader selects flat and nested JSON and rejects empty populations, so success must exercise a document. Structural guards do not establish complete semantic equivalence. The source query-operation count independently pins query-route preservation.
 * @evidence contracts/e2e.md#shared-execution This case shares the test-utils integration project and native-plugin artifact lifecycle with the other src/features exports. Its runtime rows reuse emitted schemas/callbacks in this invocation instead of starting a compiler host per input; it performs no independent installation or host launch.
 * @evidence contracts/e2e.md#state-isolation-and-reuse-validity Each invocation owns its schema/definition objects and payloads; document callers parse fresh text before conversion. Compiler-artifact reuse cannot supply a prior runtime verdict. This case opens no persistent service/process handle; fixture-reader unit temporary files are owned and released by that separate unit.
 * @evidence contracts/e2e.md#preserved-coverage Fixture enumeration additionally retains flat/nested files and rejects zero-input success; native guards and conversion assertions remain. Producer parity and structural acceptance retain their stated oracle limits rather than certifying semantic correctness.
 */
export const test_http_migrate_v32 = async (): Promise<void> => {
  const path: string = `${TestGlobal.ROOT}/examples/v3.2`;
  for (const file of await _readJsonFixturePaths(path)) {
    const swagger: OpenApiV3_2.IDocument = typia.assert<OpenApiV3_2.IDocument>(
      JSON.parse(await fs.promises.readFile(file, "utf8")),
    );
    const openapi: OpenApi.IDocument =
      OpenApiConverter.upgradeDocument(swagger);
    const migrate: IHttpMigrateApplication = HttpMigration.application(openapi);
    typia.assert(migrate);

    // Verify query method is migrated
    const queryRoutes = migrate.routes.filter((r) => r.method === "query");
    if (swagger.paths) {
      const expectedQueryCount = Object.values(swagger.paths).filter(
        (p) => p?.query !== undefined,
      ).length;
      if (queryRoutes.length !== expectedQueryCount) {
        throw new Error(
          `Expected ${expectedQueryCount} query routes but got ${queryRoutes.length}`,
        );
      }
    }
  }
};
