import {
  IHttpMigrateApplication,
  OpenApi,
  OpenApiV3_1,
} from "@typia/interface";
import { HttpMigration, OpenApiConverter } from "@typia/utils";
import fs from "fs";
import typia from "typia";

import { TestGlobal } from "../../TestGlobal";

/**
 * Verifies every OpenAPI 3.1 example document migrates to a valid application.
 *
 * Real documents exercise the whole migration pipeline.
 *
 * 1. Read each v3.1 example and validate it natively.
 * 2. Upgrade and migrate it.
 * 3. Assert the application with the native validator.
 *
 * @evidence contracts/testing.md#behavioral-verification Each example is upgraded and migrated and the result is checked by a natively generated validator.
 * @evidence contracts/testing.md#independent-expectations The interface declaration is the specification; validators are generated independently of the migrator.
 * @evidence contracts/testing.md#distinguishing-cases Every example file is a case with structural validity only.
 * @evidence contracts/testing.md#execution-ownership The test-utils test:integration command (DynamicExecutor over src/features under ttsx with the native typia plugin) discovers this exported case. typia.assert validators are generated by the native transform and the examples are read from disk.
 */
export const test_http_migrate_v31 = async (): Promise<void> => {
  const path: string = `${TestGlobal.ROOT}/examples/v3.1`;
  for (const file of await fs.promises.readdir(path)) {
    if (file.endsWith(".json") === false) continue;
    const swagger: OpenApiV3_1.IDocument = typia.assert<OpenApiV3_1.IDocument>(
      JSON.parse(await fs.promises.readFile(`${path}/${file}`, "utf8")),
    );
    const openapi: OpenApi.IDocument =
      OpenApiConverter.upgradeDocument(swagger);
    const migrate: IHttpMigrateApplication = HttpMigration.application(openapi);
    typia.assert(migrate);
  }
};
