import { IHttpMigrateApplication, OpenApi, OpenApiV3 } from "@typia/interface";
import { HttpMigration, OpenApiConverter } from "@typia/utils";
import fs from "fs";
import typia from "typia";

import { TestGlobal } from "../../TestGlobal";
import { _readJsonFixturePaths } from "../../internal/_readJsonFixturePaths";

/**
 * Verifies every OpenAPI 3.0 example document migrates to a valid application.
 *
 * Real documents exercise the whole migration pipeline.
 *
 * 1. Read each v3.0 example and validate it natively.
 * 2. Upgrade and migrate it.
 * 3. Assert the application with the native validator.
 *
 * @evidence contracts/testing.md#behavioral-verification Each example is upgraded and migrated and the result is checked by a natively generated validator.
 * @evidence contracts/testing.md#independent-expectations The interface declaration is the specification; validators are generated independently of the migrator.
 * @evidence contracts/testing.md#distinguishing-cases Every example file is a case with structural validity only.
 * @evidence contracts/testing.md#execution-ownership The test-utils test:integration command (DynamicExecutor over src/features under ttsx with the native typia plugin) discovers this exported case. typia.assert validators are generated by the native transform and the examples are read from disk.
 * @evidence contracts/e2e.md#necessary-boundary Checked-in 3.0 documents pass through native input guards, migration conversion and native output guards for the 3.0 contract. The shared reader selects flat and nested JSON and rejects empty populations, so success must exercise a document. Structural guards do not establish complete semantic equivalence.
 * @evidence contracts/e2e.md#shared-execution This case shares the test-utils integration project and native-plugin artifact lifecycle with the other src/features exports. Its runtime rows reuse emitted schemas/callbacks in this invocation instead of starting a compiler host per input; it performs no independent installation or host launch.
 * @evidence contracts/e2e.md#state-isolation-and-reuse-validity Each invocation owns its schema/definition objects and payloads; document callers parse fresh text before conversion. Compiler-artifact reuse cannot supply a prior runtime verdict. This case opens no persistent service/process handle; fixture-reader unit temporary files are owned and released by that separate unit.
 * @evidence contracts/e2e.md#preserved-coverage Fixture enumeration additionally retains flat/nested files and rejects zero-input success; native guards and conversion assertions remain. Producer parity and structural acceptance retain their stated oracle limits rather than certifying semantic correctness.
 */
export const test_http_migrate_v30 = async (): Promise<void> => {
  const path: string = `${TestGlobal.ROOT}/examples/v3.0`;
  for (const file of await _readJsonFixturePaths(path)) {
    const swagger: OpenApiV3.IDocument = typia.assert<OpenApiV3.IDocument>(
      JSON.parse(await fs.promises.readFile(file, "utf8")),
    );
    const openapi: OpenApi.IDocument =
      OpenApiConverter.upgradeDocument(swagger);
    const migrate: IHttpMigrateApplication = HttpMigration.application(openapi);
    typia.assert(migrate);
  }
};
