import typia, { tags } from "typia";

export const MemberSchema = typia.json.schemas<[IMember], "3.0">();

interface IMember {
  /** Unique user ID generated by server. */
  id: string & tags.Format<"uuid">;

  /** Email address of the member. */
  email: string & tags.Format<"email">;

  /**
   * Age of the member.
   *
   * For reference, only adult can be a member.
   */
  age: number &
    tags.Type<"uint32"> &
    tags.ExclusiveMinimum<19> &
    tags.Maximum<100>;
}
