import { TestValidator } from "@nestia/e2e";
import { ILlmApplication } from "@typia/interface";
import { TestEquality } from "@typia/template/equality";
import typia from "typia";

/**
 * Verifies typia.llm.application<IController>() emits the four declared method
 * names and documentation; typia.validate<IMember> accepts the authored member
 * and rejects the wrong scalar fields.
 *
 * CRUD method membership, parameter presence and documentation are contrasted
 * with valid versus wrong-typed member data; this does not execute the
 * controller methods or an MCP server.
 *
 * 1. Execute the native calls for the declarations and inputs in this file.
 * 2. Compare the observed schema fragments or runtime results with the stated
 *    expectations.
 *
 * @evidence contracts/testing.md#behavioral-verification typia.llm.application<IController>() emits the four declared method names and documentation; typia.validate<IMember> accepts the authored member and rejects the wrong scalar fields.
 * @evidence contracts/testing.md#independent-expectations The four names, method JSDoc and authored valid/invalid members are independent expectations from IController and IMember. No schema generated by typia supplies the expected count or validation verdict.
 * @evidence contracts/testing.md#distinguishing-cases CRUD method membership, parameter presence and documentation are contrasted with valid versus wrong-typed member data; this does not execute the controller methods or an MCP server.
 * @evidence contracts/testing.md#execution-ownership test_llm_application is the matching exported DynamicExecutor entry under test-typia-schema start (ttsx src/index.ts). It executes typia.llm.application, typia.validate through the configured native typia plugin. Private callbacks and schema projections stay part of this case; direct utility-only semantics are not relabeled as proof of the producer.
 * @evidence contracts/e2e.md#necessary-boundary The native analyzer/emitter connects the declared methods, parameter/output types, documentation and options to the runtime application/controller fields exercised here. Portable utility calls on handwritten schemas cannot prove this generated assembly or custom callback wiring.
 * @evidence contracts/e2e.md#shared-execution This case joins the existing schema-suite ttsx invocation and DynamicExecutor population; it starts no per-case project, installation, native binary build or worker. The typia.llm.application, typia.validate call sites use the same workspace/compiler configuration as their sibling cases. Compiler host and content-keyed artifact reuse are owned by ttsx, not asserted as a cold-cache transition here.
 * @evidence contracts/e2e.md#state-isolation-and-reuse-validity The source declarations, JSDoc, tags and generic configuration are part of the compilation input, so changed producer inputs require recompilation. Schema maps, payloads, callbacks and counters declared here are case-local; this file owns no process or persistent cache and shares no mutated result with another case. ttsx owns the compiler/host lifetime; cache invalidation is not this scenario.
 * @evidence contracts/e2e.md#preserved-coverage The original public calls, input declarations and assertions remain in this exported case. CRUD method membership, parameter presence and documentation are contrasted with valid versus wrong-typed member data; this does not execute the controller methods or an MCP server. Added literal or shape controls strengthen those observations; no generated schema comparison replaces an existing independent expected value, and no case is removed from execution.
 */
export const test_llm_application = (): void => {
  interface IMember {
    id: number;
    name: string;
    email: string;
  }

  interface IGetMemberInput {
    id: number;
  }
  interface ICreateMemberInput {
    name: string;
    email: string;
  }
  interface IUpdateMemberInput {
    id: number;
    name?: string;
    email?: string;
  }
  interface IDeleteMemberInput {
    id: number;
  }

  interface IController {
    /**
     * Get member by ID.
     *
     * @param input Member ID input
     *
     * @returns Member information
     */
    getMember(input: IGetMemberInput): IMember;

    /**
     * Create a new member.
     *
     * @param input Member creation input
     *
     * @returns Created member
     */
    createMember(input: ICreateMemberInput): IMember;

    /**
     * Update member information.
     *
     * @param input Member update input
     *
     * @returns Updated member
     */
    updateMember(input: IUpdateMemberInput): IMember;

    /**
     * Delete a member.
     *
     * @param input Member ID input
     */
    deleteMember(input: IDeleteMemberInput): void;
  }

  const app: ILlmApplication = typia.llm.application<IController>();

  // check functions count
  TestEquality.equals("functions count", app.functions.length, 4);

  // check function names
  const names = app.functions.map((f) => f.name);
  TestValidator.predicate("has getMember", () => names.includes("getMember"));
  TestValidator.predicate("has createMember", () =>
    names.includes("createMember"),
  );
  TestValidator.predicate("has updateMember", () =>
    names.includes("updateMember"),
  );
  TestValidator.predicate("has deleteMember", () =>
    names.includes("deleteMember"),
  );

  // check getMember function
  const getMember = app.functions.find((f) => f.name === "getMember");
  if (getMember) {
    TestValidator.predicate(
      "getMember has description",
      () =>
        getMember.description !== undefined &&
        getMember.description.includes("Get member"),
    );
    TestValidator.predicate(
      "getMember has parameters",
      () => getMember.parameters !== undefined,
    );
  }

  // check createMember function
  const createMember = app.functions.find((f) => f.name === "createMember");
  TestValidator.predicate(
    "createMember parameters exist",
    () => createMember?.parameters !== undefined,
  );
  if (createMember && createMember.parameters) {
    TestValidator.predicate(
      "createMember parameters has properties",
      () => "properties" in createMember.parameters,
    );
  }

  // validate actual data with typia.validate
  const validMember: IMember = {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
  };
  const memberValidation = typia.validate<IMember>(validMember);
  TestEquality.equals("valid member passes", memberValidation.success, true);

  const invalidMember = {
    id: "not-a-number",
    name: 123,
    email: null,
  };
  const invalidValidation = typia.validate<IMember>(invalidMember);
  TestEquality.equals("invalid member fails", invalidValidation.success, false);
};
