import { OpenApi } from "../openapi/OpenApi";
import { OpenApiV3 } from "../openapi/OpenApiV3";

/**
 * Collection of JSON schemas generated from TypeScript types.
 *
 * `IJsonSchemaCollection` is generated by `typia.json.schemas<[T1, T2, ...]>()`.
 * Supports both OpenAPI v3.0 and v3.1 specifications.
 *
 * @template Version OpenAPI version ("3.0" or "3.1")
 * @template Types Original TypeScript types
 * @author Jeongho Nam - https://github.com/samchon
 */
export type IJsonSchemaCollection<
  Version extends "3.0" | "3.1" = "3.1",
  Types = unknown[],
> = Version extends "3.0"
  ? IJsonSchemaCollection.IV3_0<Types>
  : IJsonSchemaCollection.IV3_1<Types>;

export namespace IJsonSchemaCollection {
  /**
   * JSON Schema collection for OpenAPI v3.0.
   *
   * @template Types Original TypeScript types
   */
  export interface IV3_0<Types = unknown[]> {
    /** OpenAPI version. */
    version: "3.0";

    /** Generated JSON schemas, one per input type. */
    schemas: OpenApiV3.IJsonSchema[];

    /** Reusable schema components for `$ref` referencing. */
    components: OpenApiV3.IComponents;

    /** @internal Type marker for compile-time tracking. */
    __types?: Types | undefined;
  }

  /**
   * JSON Schema collection for OpenAPI v3.1.
   *
   * @template Types Original TypeScript types
   */
  export interface IV3_1<Types = unknown[]> {
    /** OpenAPI version. */
    version: "3.1";

    /** Reusable schema components for `$ref` referencing. */
    components: OpenApi.IComponents;

    /** Generated JSON schemas, one per input type. */
    schemas: OpenApi.IJsonSchema[];

    /** @internal Type marker for compile-time tracking. */
    __types?: Types | undefined;
  }
}
