import { OpenApi } from "../openapi/OpenApi";
import { OpenApiV3 } from "../openapi/OpenApiV3";

/**
 * Single JSON schema unit for one TypeScript type.
 *
 * `IJsonSchemaUnit` represents a complete JSON schema for a single TypeScript
 * type, including the main schema definition and any referenced component
 * schemas. Generated by `typia.json.schema<T>()` at compile time.
 *
 * The result contains:
 *
 * - {@link IV3_0.schema | schema}: The main JSON schema for the type
 * - {@link IV3_0.components | components}: Shared schemas referenced via `$ref`
 * - {@link IV3_0.__type | __type}: Phantom property for TypeScript type inference
 *
 * Use this for single-type schema generation. For multiple types, see
 * {@link IJsonSchemaCollection}. For function schemas, see
 * {@link IJsonSchemaApplication}.
 *
 * @author Jeongho Nam - https://github.com/samchon
 *
 * @template Version OpenAPI version ("3.0" or "3.1")
 * @template Type Original TypeScript type
 *
 * @evidence contracts/common.md#principled-implementation A distributive conditional selects the version-literal variant and its matching OpenApiV3 or normalized OpenApi schema types; Type is carried only by an optional phantom member. A version union therefore remains a union of correlated versioned records.
 * @evidence contracts/common.md#clear-and-simple-design The alias owns dialect selection while the namespace owns the two result shapes. It does not duplicate schema definitions or a runtime converter.
 * @evidence contracts/common.md#prohibited-implementation-shortcuts The 3.0 and 3.1 literals are supported wire dialects, not fixture exceptions. This type neither validates schemas nor requires a runtime phantom value.
 * @evidence contracts/common.md#meaningful-documentation The native comment explains one root schema, shared components, the generic parameters and adjacent single/multiple/application APIs; member comments identify phantom inference and generator omission.
 */
export type IJsonSchemaUnit<
  Version extends "3.0" | "3.1" = "3.1",
  Type = unknown,
> = Version extends "3.0"
  ? IJsonSchemaUnit.IV3_0<Type>
  : IJsonSchemaUnit.IV3_1<Type>;

/** Version-specific units containing JSON schemas and their shared definitions. */
export namespace IJsonSchemaUnit {
  /**
   * JSON Schema unit for OpenAPI v3.0 specification.
   *
   * Uses OpenAPI v3.0 compatible JSON Schema format. In v3.0, nullable types
   * are expressed with `nullable: true` rather than v3.1's `type: ["string",
   * "null"]`.
   *
   * @template Type Original TypeScript type for phantom type preservation
   *
   * @evidence contracts/common.md#principled-implementation The 3.0 literal discriminator accompanies one root schema and components typed in the OpenApiV3 dialect. The optional Type member preserves generic inference; the generator omits it rather than serializing TypeScript values.
   * @evidence contracts/common.md#clear-and-simple-design The record separates the root from shared component definitions, enabling recursive references without duplicating the component graph. Dialect-specific field types remain local to this variant.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts The wire version and schema fields express the supported 3.0 result contract. Optional phantom typing is not a runtime guard and does not prevent callers from constructing a value with that property.
   * @evidence contracts/common.md#meaningful-documentation Member comments explain the target schema, reference ownership and generator omission of the phantom property; the variant comment identifies dialect differences and its inference generic.
   */
  export interface IV3_0<Type> {
    /**
     * OpenAPI specification version.
     *
     * Always `"3.0"` for this variant. Use this discriminator to determine
     * which schema format is in use.
     */
    version: "3.0";

    /**
     * The main JSON schema definition for the type.
     *
     * Contains the complete schema for the target TypeScript type. May include
     * `$ref` references to schemas in {@link components}.
     */
    schema: OpenApiV3.IJsonSchema;

    /**
     * Reusable schema definitions for `$ref` references.
     *
     * Contains named schemas that can be referenced throughout the main schema.
     * Essential for recursive types and reducing duplication.
     */
    components: OpenApiV3.IComponents;

    /**
     * Phantom property for TypeScript generic type preservation.
     *
     * The generated result omits this property. It preserves the `Type` generic
     * parameter for type inference and should not be read as schema data.
     */
    __type?: Type | undefined;
  }

  /**
   * JSON Schema unit for OpenAPI v3.1 specification.
   *
   * Uses OpenAPI v3.1 compatible JSON Schema format. v3.1 aligns more closely
   * with JSON Schema draft 2020-12, supporting features like `type` arrays for
   * nullable types and `const` values.
   *
   * @template Type Original TypeScript type for phantom type preservation
   *
   * @evidence contracts/common.md#principled-implementation The 3.1 literal discriminator accompanies one root schema and components typed in the normalized OpenApi dialect. The optional Type member preserves generic inference; the generator omits it rather than serializing TypeScript values.
   * @evidence contracts/common.md#clear-and-simple-design The record separates the root from shared component definitions, enabling recursive references without duplicating the component graph. Dialect-specific field types remain local to this variant.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts The wire version and schema fields express the supported 3.1 result contract. Optional phantom typing is not a runtime guard and does not prevent callers from constructing a value with that property.
   * @evidence contracts/common.md#meaningful-documentation Member comments explain the target schema, reference ownership and generator omission of the phantom property; the variant comment identifies dialect differences and its inference generic.
   */
  export interface IV3_1<Type> {
    /**
     * OpenAPI specification version.
     *
     * Always `"3.1"` for this variant. Use this discriminator to determine
     * which schema format is in use.
     */
    version: "3.1";

    /**
     * The main JSON schema definition for the type.
     *
     * Contains the complete schema for the target TypeScript type. May include
     * `$ref` references to schemas in {@link components}.
     */
    schema: OpenApi.IJsonSchema;

    /**
     * Reusable schema definitions for `$ref` references.
     *
     * Contains named schemas that can be referenced throughout the main schema.
     * Essential for recursive types and reducing duplication.
     */
    components: OpenApi.IComponents;

    /**
     * Phantom property for TypeScript generic type preservation.
     *
     * The generated result omits this property. It preserves the `Type` generic
     * parameter for type inference and should not be read as schema data.
     */
    __type?: Type | undefined;
  }
}
