import { IValidation } from "./IValidation";

/**
 * LLM evaluation questions with a converting validator.
 *
 * `ILlmEvaluation<T>` is generated by `typia.llm.evaluation<T>()`. Each leaf
 * property of `T` becomes one question for an evaluation model, such as
 * TypeSafe's Jev, or OpenAI, Anthropic, and Google through Vercel AI SDK's
 * `experimental_evaluate()`:
 *
 * - `boolean` becomes an {@link ILlmEvaluation.IBoolean} question
 * - A string enum or string literal union becomes an
 *   {@link ILlmEvaluation.IChoice} question
 * - A numeric enum or numeric literal union becomes an
 *   {@link ILlmEvaluation.IScore} question
 * - An array of a string literal union or string enum becomes one
 *   {@link ILlmEvaluation.IBoolean} question per member, asking in English
 *   whether that member applies
 * - A nested object is flattened, one question per leaf
 *
 * Workflow:
 *
 * 1. Pass {@link questions} to the evaluation model with a shared state
 * 2. Receive the answer map keyed by the same question IDs
 * 3. Call {@link validate} to check the answers and fold them back into `T`
 *
 * Probabilities are calibrated only on native evaluation models such as Jev.
 * The AI SDK adapters for OpenAI, Anthropic, and Google ask a language model to
 * write each number itself, and return no choice or score distribution.
 *
 * This interface is experimental. It follows Vercel AI SDK's evaluation model
 * specification, which is itself experimental and may change in patch
 * releases.
 *
 * @author Jeongho Nam - https://github.com/samchon
 * @template T The decision type
 */
export interface ILlmEvaluation<T = unknown> {
  /**
   * Question map, keyed by readable property paths.
   *
   * Pass it as the `questions` of Vercel AI SDK's `experimental_evaluate()` as
   * it is. Jev's own wire format, shared by TypeSafe's API and OpenRouter's
   * Decisions API, spells the boolean question type `"noul"`;
   * `toJevQuestions()` from `@typia/jev` converts the questions.
   *
   * Jev evaluates each question independently, while the AI SDK adapters for
   * language models only instruct the model to. A key is not a part of the
   * question text. The `instructions` come from the property's JSDoc
   * description, and choice or score criteria from the enum members' JSDoc
   * descriptions or `tags.Constant` descriptions.
   */
  questions: Record<string, ILlmEvaluation.IQuestion>;

  /**
   * Validate an answer map and fold it back into `T`.
   *
   * Unlike `ILlmStructuredOutput.validate()`, the input is not a `T` shaped
   * value but the model's answer map, keyed by the {@link questions} keys. It
   * accepts both the neutral boolean answer (`{ type: "boolean", probability
   * }`) and TypeSafe's native one (`{ type: "noul", noul }`).
   *
   * Conversion rules:
   *
   * - A boolean is `true` when its probability reaches the threshold of
   *   `tags.Probability<N>` or `@probability N`, `0.5` by default
   * - A choice is the returned option
   * - A score is the level with the highest probability when the answer has
   *   `probabilities`, otherwise the level nearest to `score`
   * - A choice option or score level with a probability requirement fails
   *   validation when it is selected below that requirement, or when the answer
   *   has no `probabilities` to prove it
   *
   * @param answers Answer map from the evaluation model
   * @returns Validation result with the converted `T` on success
   */
  validate: (answers: unknown) => IValidation<T>;
}
export namespace ILlmEvaluation {
  /** Any evaluation question. */
  export type IQuestion = IChoice | IScore | IBoolean;

  /** Question selecting exactly one of the declared options. */
  export interface IChoice {
    /** Discriminator. */
    type: "choice";

    /** What to decide, from the property's JSDoc description. */
    instructions: string;

    /**
     * Options mapped to their descriptions.
     *
     * The keys are the literal values. A value is `null` when the option has no
     * description.
     */
    criteria: Record<string, string | null>;
  }

  /** Question placing the state on ordered levels. */
  export interface IScore {
    /** Discriminator. */
    type: "score";

    /** What to decide, from the property's JSDoc description. */
    instructions: string;

    /**
     * Level descriptions, from the lowest to the highest.
     *
     * Level `i` is the `i`-th smallest numeric value. A level without a
     * description is described by its value. There are always at least two
     * levels, because a single numeric literal is a compile error.
     */
    criteria: [string, string, ...string[]];
  }

  /** Question estimating the probability of "yes". */
  export interface IBoolean {
    /** Discriminator. */
    type: "boolean";

    /** What to decide, from the property's JSDoc description. */
    instructions: string;
  }
}
