import { ILlmSchema } from "./ILlmSchema";
import { IValidation } from "./IValidation";

/**
 * LLM function calling metadata.
 *
 * `ILlmFunction` describes a single callable function for LLM agents. Generated
 * as part of {@link ILlmApplication} by `typia.llm.application<App>()`.
 *
 * Contains the function {@link name} (max 64 chars for OpenAI),
 * {@link parameters} schema for input types, optional {@link output} schema for
 * return type, and {@link description} for LLM to understand the function's
 * purpose.
 *
 * The built-in {@link validate} function checks LLM-generated arguments against
 * the schema, enabling auto-correction when the LLM makes type errors (e.g.,
 * returning `"123"` instead of `123`).
 *
 * Use {@link separated} when some parameters require human input (files,
 * passwords) via {@link ILlmApplication.IConfig.separate}.
 *
 * @author Jeongho Nam - https://github.com/samchon
 */
export interface ILlmFunction {
  /**
   * Function name for LLM invocation.
   *
   * The identifier used by the LLM to call this function. Must be unique within
   * the application. OpenAI limits function names to 64 characters.
   *
   * @maxLength 64
   */
  name: string;

  /**
   * Schema for function parameters.
   *
   * Defines the expected argument types as a JSON Schema object. Contains
   * `$defs` for shared type definitions and `properties` for each named
   * parameter.
   */
  parameters: ILlmSchema.IParameters;

  /**
   * Parameters split between LLM and human input.
   *
   * Present when {@link ILlmApplication.IConfig.separate} is configured. Allows
   * separating parameters that the LLM can fill from those requiring human
   * input (e.g., file uploads, passwords).
   */
  separated?: ILlmFunction.ISeparated;

  /**
   * Schema for the return type.
   *
   * Defines the expected output type as a JSON Schema. `undefined` when the
   * function returns `void` or has no meaningful return value.
   */
  output?: ILlmSchema | undefined;

  /**
   * Human-readable function description.
   *
   * Explains what the function does, when to use it, and any important
   * considerations. This description is crucial for LLMs to understand when to
   * invoke this function. Extracted from JSDoc comments.
   */
  description?: string | undefined;

  /**
   * Whether this function is deprecated.
   *
   * When `true`, indicates the function should no longer be used. LLMs may
   * still invoke deprecated functions but should prefer non-deprecated
   * alternatives when available.
   */
  deprecated?: boolean | undefined;

  /**
   * Category tags for function organization.
   *
   * Extracted from `@tag` JSDoc annotations. Useful for grouping related
   * functions and filtering the function list.
   */
  tags?: string[] | undefined;

  /**
   * Validates LLM-generated arguments against the schema.
   *
   * LLMs frequently make type errors such as returning strings instead of
   * numbers or missing required properties. Use this validator to check
   * arguments before execution.
   *
   * When validation fails, use `stringifyValidationFailure()` from
   * `@typia/utils` to format the error for LLM feedback. The formatted output
   * shows the invalid JSON with inline error comments, helping the LLM
   * understand and correct its mistakes in the next turn.
   *
   * @param args The arguments generated by the LLM
   * @returns Validation result with success status and any errors
   * @see stringifyValidationFailure Format errors for LLM auto-correction
   */
  validate: (args: unknown) => IValidation<unknown>;
}
export namespace ILlmFunction {
  /**
   * Separated parameter schemas for hybrid LLM/human input.
   *
   * When a function has parameters that cannot or should not be filled by the
   * LLM (e.g., file uploads, passwords, sensitive data), the parameters are
   * split into two schemas.
   */
  export interface ISeparated {
    /**
     * Parameters the LLM should fill.
     *
     * Contains only the parameters that are safe and appropriate for the LLM to
     * generate values for.
     */
    llm: ILlmSchema.IParameters;

    /**
     * Parameters requiring human input.
     *
     * Contains parameters that must be provided by the user directly, such as
     * file uploads, passwords, or other sensitive data. `null` when all
     * parameters can be filled by the LLM.
     */
    human: ILlmSchema.IParameters | null;

    /**
     * Validates the LLM portion of separated parameters.
     *
     * Validates only the LLM-fillable portion, allowing human parameters to be
     * validated separately with appropriate handling.
     *
     * When validation fails, use `stringifyValidationFailure()` from
     * `@typia/utils` to format the error for LLM feedback.
     *
     * @see stringifyValidationFailure Format errors for LLM auto-correction
     */
    validate?: ((args: unknown) => IValidation<unknown>) | undefined;
  }
}
