import { tags } from "..";
import { IJsonParseResult } from "./IJsonParseResult";
import { ILlmSchema } from "./ILlmSchema";
import { IValidation } from "./IValidation";

/**
 * LLM function calling schema for TypeScript functions.
 *
 * Generated by `typia.llm.application<App>()` as part of
 * {@link ILlmApplication}.
 *
 * - {@link name}: Function identifier (max 64 chars)
 * - {@link parameters}: Input schema, {@link output}: Return schema
 * - {@link description}: Guides LLM function selection
 * - {@link parse}: Lenient JSON parser with type coercion
 * - {@link validate}: Argument validator for LLM error correction
 *
 * @author Jeongho Nam - https://github.com/samchon
 *
 * @evidence contracts/common.md#principled-implementation The record contains the name, parameter schema, optional output schema and description, deprecation, tags and three functions for parsing, coercing and validating arguments. Name is limited to 64 characters through a MaxLength tag, matching the native check in the application programmer; the output is optional because a void function has none.
 * @evidence contracts/common.md#clear-and-simple-design Data fields and operations are kept in one record because consumers hand it to a framework as a unit.
 * @evidence contracts/common.md#prohibited-implementation-shortcuts The member functions are supplied by the generator and the interface does not implement or patch them.
 * @evidence contracts/common.md#meaningful-documentation The comment lists the main members and every member explains its role, the lenient parsing behavior and the name limit.
 */
export interface ILlmFunction {
  /**
   * Function name for LLM invocation.
   *
   * The identifier used by the LLM to call this function. Must be unique within
   * the application.
   *
   * Limited to 64 characters: `typia.llm.application` rejects a longer name,
   * and {@link IHttpLlmApplication.IConfig.maxLength} shortens one.
   */
  name: string & tags.MaxLength<64>;

  /**
   * Schema for function parameters.
   *
   * Defines the expected argument types as a JSON Schema object. Contains
   * `$defs` for shared type definitions and `properties` for each named
   * parameter.
   */
  parameters: ILlmSchema.IParameters;

  /**
   * Schema for the return type.
   *
   * Defines the expected output type as an object parameters schema, wrapping
   * the return type in an {@link ILlmSchema.IParameters} object with `$defs` for
   * shared type definitions and `properties` for the structured output.
   *
   * `undefined` when the function returns `void` or has no meaningful return
   * value.
   */
  output?: ILlmSchema.IParameters | undefined;

  /**
   * Human-readable function description.
   *
   * Explains what the function does, when to use it, and any important
   * considerations. This description is crucial for LLMs to understand when to
   * invoke this function. Extracted from JSDoc comments.
   */
  description?: string | undefined;

  /**
   * Whether this function is deprecated.
   *
   * When `true`, indicates the function should no longer be used. LLMs may
   * still invoke deprecated functions but should prefer non-deprecated
   * alternatives when available.
   */
  deprecated?: boolean | undefined;

  /**
   * Category tags for function organization.
   *
   * Extracted from `@tag` JSDoc annotations. Useful for grouping related
   * functions and filtering the function list.
   */
  tags?: string[] | undefined;

  /**
   * Lenient JSON parser with schema-based coercion.
   *
   * Handles incomplete/malformed JSON commonly produced by LLMs:
   *
   * - Unclosed brackets, strings, trailing commas
   * - JavaScript-style comments (`//` and multi-line)
   * - Unquoted object keys, incomplete keywords (`tru`, `fal`, `nul`)
   * - Markdown code block extraction, junk prefix skipping
   *
   * Also coerces double-stringified values (`"42"` → `42`) using the
   * {@link parameters} schema.
   *
   * Type validation is NOT performed — use {@link validate} after parsing.
   *
   * If the SDK (e.g., LangChain, Vercel AI, MCP) already parses JSON internally
   * and provides a pre-parsed object, use {@link coerce} instead to apply
   * schema-based type coercion without re-parsing.
   *
   * @param str Raw JSON string from LLM output
   *
   * @returns Parse result with data on success, or partial data with errors
   *
   * @evidence contracts/common.md#principled-implementation Its signature takes the raw string and returns IJsonParseResult of unknown, which separates recovered data from failure; the comment states that it coerces by schema but does not validate types.
   * @evidence contracts/common.md#clear-and-simple-design A function-valued property with a single argument.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts It makes no claim of type safety and sends callers to validate.
   * @evidence contracts/common.md#meaningful-documentation The comment lists the malformed JSON it recovers, the coercion it does, and when to use coerce instead.
   */
  parse: (str: string) => IJsonParseResult<unknown>;

  /**
   * Coerce pre-parsed arguments to match expected schema types.
   *
   * **Use this only when the SDK (e.g., LangChain, Vercel AI, MCP) already
   * parses JSON internally.** For raw JSON strings from LLM output, use
   * {@link parse} instead — it handles both lenient parsing and type coercion in
   * one step.
   *
   * LLMs often return values with incorrect types even after parsing:
   *
   * - `"42"` → `42` (when schema expects number)
   * - `"true"` → `true` (when schema expects boolean)
   * - `"null"` → `null` (when schema expects null)
   * - `"{...}"` → `{...}` (when schema expects object)
   * - `"[...]"` → `[...]` (when schema expects array)
   *
   * This function recursively coerces these double-stringified values based on
   * the {@link parameters} schema.
   *
   * Type validation is NOT performed — use {@link validate} after coercion.
   *
   * @param data Pre-parsed arguments object from SDK
   *
   * @returns Coerced arguments with corrected types
   *
   * @evidence contracts/common.md#principled-implementation Its input is already parsed data and the output has corrected types, so the function is a schema-directed transformation with no parsing; the signature returns unknown because correctness is established by validate.
   * @evidence contracts/common.md#clear-and-simple-design A function-valued property with a single argument.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts It does not validate and says so.
   * @evidence contracts/common.md#meaningful-documentation The comment warns to use it only for pre-parsed input, lists coercion examples and says validation is separate.
   */
  coerce: (data: unknown) => unknown;

  /**
   * Validates LLM-generated arguments against the schema.
   *
   * LLMs frequently make type errors such as returning strings instead of
   * numbers or missing required properties. Use this validator to check
   * arguments before execution.
   *
   * When validation fails, use {@link LlmJson.stringify} from `@typia/utils` to
   * format the error for LLM feedback. The formatted output shows the invalid
   * JSON with inline error comments, helping the LLM understand and correct its
   * mistakes in the next turn.
   *
   * @param args The arguments generated by the LLM
   *
   * @returns Validation result with success status and any errors
   *
   * @evidence contracts/common.md#principled-implementation The argument is unknown and the result is IValidation of unknown, so a caller must narrow by success before use; failure carries the structured errors for feedback to the model.
   * @evidence contracts/common.md#clear-and-simple-design A function-valued property with one argument.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts It reports errors instead of throwing or coercing.
   * @evidence contracts/common.md#meaningful-documentation The comment explains the use for feedback with the stringify helper and links the formatting utility.
   *
   * @see stringifyValidationFailure Format errors for LLM auto-correction
   */
  validate: (args: unknown) => IValidation<unknown>;
}
