import { IValidation } from "./IValidation";

/**
 * LLM evaluation questions with a checked answer decoder.
 *
 * `ILlmEvaluation<T>` is generated by `typia.llm.evaluation<T>()`. Each leaf
 * property of `T` becomes one question for an evaluation model, such as
 * TypeSafe's Jev, or OpenAI, Anthropic, and Google through Vercel AI SDK's
 * `experimental_evaluate()`:
 *
 * - `boolean` becomes an {@link ILlmEvaluation.IBoolean} question
 * - A string enum or string literal union becomes an
 *   {@link ILlmEvaluation.IChoice} question
 * - A numeric enum or numeric literal union becomes an
 *   {@link ILlmEvaluation.IScore} question
 * - An array of a string literal union or string enum becomes one
 *   {@link ILlmEvaluation.IBoolean} question per member, asking in English
 *   whether that member applies
 * - A nested object is flattened, one question per leaf
 *
 * Workflow:
 *
 * 1. Pass {@link questions} to the evaluation model with a shared state
 * 2. Receive the answer map keyed by the same question IDs
 * 3. Call {@link decode} to check the answers and fold them back into `T`
 *
 * Probabilities are calibrated only on native evaluation models such as Jev.
 * The AI SDK adapters for OpenAI, Anthropic, and Google ask a language model to
 * write each number itself, and return no choice or score distribution.
 *
 * This interface is experimental. It follows Vercel AI SDK's evaluation model
 * specification, which is itself experimental and may change in patch releases.
 * Refinements that the answer decoder cannot enforce are compile errors, so a
 * successful {@link decode} does not require a second `typia.validate<T>()`.
 *
 * @author Jeongho Nam - https://github.com/samchon
 * @template T The decision type
 */
export interface ILlmEvaluation<T = unknown> {
  /**
   * Question map, keyed by readable property paths.
   *
   * Pass it as the `questions` of Vercel AI SDK's `experimental_evaluate()` as
   * it is. Jev's own wire format, shared by TypeSafe's API and OpenRouter's
   * Decisions API, spells the boolean question type `"noul"`;
   * `toJevQuestions()` from `@typia/jev` converts the questions.
   *
   * Jev evaluates each question independently, while the AI SDK adapters for
   * language models only instruct the model to. A key is not a part of the
   * question text. The `instructions` come from the property's JSDoc
   * description, and choice or score criteria from the enum members' JSDoc
   * descriptions.
   */
  questions: Record<string, ILlmEvaluation.IQuestion>;

  /**
   * Check an answer map and decode it into `T`.
   *
   * Unlike `typia.validate<T>()` or `ILlmStructuredOutput.validate()`, this
   * method transforms a model answer map into a different shape. It checks the
   * answers keyed by {@link questions} and returns the converted `T` on success.
   * It accepts both the neutral boolean answer (`{ type: "boolean", probability
   * }`) and TypeSafe's native one (`{ type: "noul", noul }`).
   *
   * Conversion rules:
   *
   * - A boolean is `true` when its probability reaches the threshold of
   *   `tags.Probability<N>` or `@probability N`, `0.5` by default
   * - A choice is the returned option
   * - A score is the level with the highest probability when the answer has
   *   `probabilities`, otherwise the level nearest to `score`
   * - A choice option or score level with a probability requirement fails
   *   validation when it is selected below that requirement, or when the answer
   *   has no `probabilities` to prove it
   * - Once one choice, score, or set member declares a probability requirement,
   *   every member must declare one or inherit a property `@probability`
   *   default
   * - An optional choice or score `probabilities` map must be complete, sum to
   *   one, and agree with the selected choice or score, following AI SDK's
   *   evaluation answer contract and any declared rounding precision
   *
   * @param answers Answer map from the evaluation model
   * @param rounding Optional provider-declared precision. Pass AI SDK's
   *   `result.rounding` here; without it, distribution checks remain strict.
   * @returns Validation result with the converted `T` on success
   */
  decode: (
    answers: unknown,
    rounding?: ILlmEvaluation.IRounding,
  ) => IValidation<T>;
}
export namespace ILlmEvaluation {
  /** Decimal precision declared by an evaluation model for its answer values. */
  export interface IRounding {
    probabilityDecimals?: number;
    scoreDecimals?: number;
  }

  /** Any evaluation question. */
  export type IQuestion = IChoice | IScore | IBoolean;

  /** Question selecting exactly one of the declared options. */
  export interface IChoice {
    /** Discriminator. */
    type: "choice";

    /** What to decide, from the property's JSDoc description. */
    instructions: string;

    /**
     * The alternatives the evaluation model must distinguish.
     *
     * Each key is one string literal value that the model may select, and its
     * value explains when that option applies. The explanation comes from the
     * enum member's JSDoc description. It is `null` when the member has no
     * description, in which case the model sees only the literal key.
     *
     * For example, an enum member `billing = "billing"` documented as `Payments
     * and refunds` becomes `{ billing: "Payments and refunds" }`.
     */
    criteria: Record<string, string | null>;
  }

  /** Question placing the state on ordered levels. */
  export interface IScore {
    /** Discriminator. */
    type: "score";

    /** What to decide, from the property's JSDoc description. */
    instructions: string;

    /**
     * The ordered levels the evaluation model uses to place the state.
     *
     * Each entry explains when its level applies and comes from that numeric
     * enum member's JSDoc description. The entries are ordered by the members'
     * numeric values, not by declaration order. The wire-level score is a
     * possibly fractional position on the array's index scale;
     * {@link ILlmEvaluation.decode} selects a level and maps it back to the
     * corresponding numeric value of `T`.
     *
     * For example, members `calm = 10` and `angry = 30`, documented as `No
     * frustration` and `Clearly frustrated`, produce `["No frustration",
     * "Clearly frustrated"]`. A level without a description uses its numeric
     * value as text. There are always at least two levels, because a single
     * numeric literal is a compile error.
     */
    criteria: [string, string, ...string[]];
  }

  /** Question estimating the probability of "yes". */
  export interface IBoolean {
    /** Discriminator. */
    type: "boolean";

    /** What to decide, from the property's JSDoc description. */
    instructions: string;
  }
}
