import { tags } from "../index";
import { IJsonSchemaAttribute } from "./IJsonSchemaAttribute";

/**
 * Type schema for LLM function calling.
 *
 * `ILlmSchema` is a JSON Schema subset designed for LLM function calling
 * compatibility. The subset omits tuples, `const`, and mixed union types.
 *
 * Generated by `typia.llm.schema<T>()` for single types or included in
 * {@link ILlmApplication} via `typia.llm.application<Class>()`. Shared type
 * definitions use `$defs` with `$ref` references to reduce duplication and
 * handle recursive structures.
 *
 * Set {@link ILlmSchema.IConfig.strict} to `true` for OpenAI's structured output
 * mode: every property becomes `required` and `additionalProperties` is forced
 * to `false`.
 *
 * @author Jeongho Nam - https://github.com/samchon
 *
 * @evidence contracts/common.md#principled-implementation The union of ten variants each keyed by its `type` or `$ref` or `anyOf` shape matches the LLM-compatible JSON Schema subset, which omits tuples, const and mixed unions; strict mode additionally requires properties and forbids additional ones.
 * @evidence contracts/common.md#clear-and-simple-design One alias over the variants in the namespace, each extending the JSON schema attribute family.
 * @evidence contracts/common.md#prohibited-implementation-shortcuts It narrows the schema space to what providers accept and does not carry provider-specific escape hatches.
 * @evidence contracts/common.md#meaningful-documentation The comment states what is omitted, how definitions are shared with `$defs` and what strict mode changes, and links the guide.
 *
 * @see https://typia.io/docs/llm/application
 */
export type ILlmSchema =
  | ILlmSchema.IBoolean
  | ILlmSchema.IInteger
  | ILlmSchema.INumber
  | ILlmSchema.IString
  | ILlmSchema.IArray
  | ILlmSchema.IObject
  | ILlmSchema.IReference
  | ILlmSchema.IAnyOf
  | ILlmSchema.INull
  | ILlmSchema.IUnknown;
export namespace ILlmSchema {
  /**
   * Configuration options for LLM schema generation.
   *
   * Controls how TypeScript types are converted to LLM-compatible JSON schemas.
   * These settings affect OpenAI structured output compatibility.
   *
   * @evidence contracts/common.md#principled-implementation The only setting is the strict flag that selects OpenAI structured output behavior: every property required and additional properties false.
   * @evidence contracts/common.md#clear-and-simple-design One required boolean field.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts A plain configuration record.
   * @evidence contracts/common.md#meaningful-documentation The comment gives the default and the effect of the flag.
   */
  export interface IConfig {
    /**
     * Whether to enable strict mode (OpenAI structured output).
     *
     * When `true`, all properties become required and `additionalProperties` is
     * forced to `false`.
     *
     * @default false
     */
    strict: boolean;
  }

  /**
   * Function parameters schema with shared type definitions.
   *
   * Extends the object schema to include a `$defs` map for named type
   * definitions that can be referenced via `$ref`. This structure allows
   * recursive types and reduces schema duplication.
   *
   * The `additionalProperties` is always `false` for parameters to ensure
   * strict argument validation and prevent unexpected properties.
   *
   * @evidence contracts/common.md#principled-implementation It extends the object schema without its additionalProperties and redeclares that field as `false`, adding a `$defs` map for named definitions, so arguments cannot include unknown properties and recursive types can be referenced.
   * @evidence contracts/common.md#clear-and-simple-design Omit plus two members expresses the delta from IObject precisely.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts It does not allow a looser setting than the strict argument contract.
   * @evidence contracts/common.md#meaningful-documentation The comment explains `$defs`, the fixed false value and why it is fixed.
   */
  export interface IParameters extends Omit<IObject, "additionalProperties"> {
    /**
     * Named schema definitions for reference.
     *
     * Contains type definitions that can be referenced throughout the schema
     * using `$ref: "#/$defs/TypeName"`. Definition names are encoded as one RFC
     * 6901 token in URI-fragment form. Essential for recursive types and shared
     * structures.
     */
    $defs: Record<string, ILlmSchema>;

    /**
     * Whether additional properties are allowed.
     *
     * Always `false` for function parameters to ensure strict type checking.
     * This prevents LLMs from hallucinating extra properties.
     */
    additionalProperties: false;
  }

  /**
   * Boolean type schema.
   *
   * Represents a JSON Schema boolean type with optional enum constraints and
   * default value. Used for true/false parameters and flags.
   *
   * @evidence contracts/common.md#principled-implementation Boolean extends the JSON schema boolean attribute with an optional enum of booleans and an optional default.
   * @evidence contracts/common.md#clear-and-simple-design Two optional members added to the shared attribute.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts A plain data record.
   * @evidence contracts/common.md#meaningful-documentation The comment says what the constraints are and notes that enum is rarely used.
   */
  export interface IBoolean extends IJsonSchemaAttribute.IBoolean {
    /**
     * Allowed boolean values.
     *
     * Restricts the value to specific boolean literals. Typically unused since
     * booleans only have two possible values, but supported for consistency
     * with other types.
     */
    enum?: Array<boolean>;

    /**
     * Default value when not provided.
     *
     * The boolean value to use when the LLM omits this parameter.
     */
    default?: boolean;
  }

  /**
   * Integer type schema.
   *
   * Represents a JSON Schema integer type with numeric constraints. Maps to
   * TypeScript `number` with integer validation. Supports range constraints,
   * enum restrictions, and divisibility checks.
   *
   * @evidence contracts/common.md#principled-implementation Constraint fields are typed as `number & Type<"int64">`, which restricts the schema to whole numbers in the 64-bit range, and multipleOf additionally requires uint64 and a positive value, since a zero or negative divisor is meaningless.
   * @evidence contracts/common.md#clear-and-simple-design The integer constraints repeat across fields by the same tag type, and each is a separate member because they are independent in JSON Schema.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts It uses the declared type tags and not custom range logic.
   * @evidence contracts/common.md#meaningful-documentation Each member says what it constrains and gives examples for multipleOf.
   */
  export interface IInteger extends IJsonSchemaAttribute.IInteger {
    /**
     * Allowed integer values.
     *
     * Restricts the value to specific integer literals. Useful for representing
     * enum-like integer codes or limited value sets.
     */
    enum?: Array<number & tags.Type<"int64">>;

    /**
     * Default value when not provided.
     *
     * The integer value to use when the LLM omits this parameter.
     */
    default?: number & tags.Type<"int64">;

    /**
     * Minimum value (inclusive).
     *
     * The value must be greater than or equal to this number.
     */
    minimum?: number & tags.Type<"int64">;

    /**
     * Maximum value (inclusive).
     *
     * The value must be less than or equal to this number.
     */
    maximum?: number & tags.Type<"int64">;

    /**
     * Exclusive minimum value.
     *
     * The value must be strictly greater than this number.
     */
    exclusiveMinimum?: number & tags.Type<"int64">;

    /**
     * Exclusive maximum value.
     *
     * The value must be strictly less than this number.
     */
    exclusiveMaximum?: number & tags.Type<"int64">;

    /**
     * Value must be divisible by this number.
     *
     * Used for constraints like "must be even" (multipleOf: 2) or "must be a
     * multiple of 100" (multipleOf: 100).
     */
    multipleOf?: number & tags.Type<"uint64"> & tags.ExclusiveMinimum<0>;
  }

  /**
   * Number (floating-point) type schema.
   *
   * Represents a JSON Schema number type for floating-point values. Maps to
   * TypeScript `number` type. Supports range constraints, enum restrictions,
   * and precision checks via multipleOf.
   *
   * @evidence contracts/common.md#principled-implementation Number constraints are plain numbers with the same keywords as integer, with multipleOf required to be exclusively above zero.
   * @evidence contracts/common.md#clear-and-simple-design Seven optional members with no helper types.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts A plain data record.
   * @evidence contracts/common.md#meaningful-documentation Each member states its meaning and examples for decimal precision.
   */
  export interface INumber extends IJsonSchemaAttribute.INumber {
    /**
     * Allowed numeric values.
     *
     * Restricts the value to specific number literals. Useful for representing
     * specific valid values like percentages or rates.
     */
    enum?: Array<number>;

    /**
     * Default value when not provided.
     *
     * The number to use when the LLM omits this parameter.
     */
    default?: number;

    /**
     * Minimum value (inclusive).
     *
     * The value must be greater than or equal to this number.
     */
    minimum?: number;

    /**
     * Maximum value (inclusive).
     *
     * The value must be less than or equal to this number.
     */
    maximum?: number;

    /**
     * Exclusive minimum value.
     *
     * The value must be strictly greater than this number.
     */
    exclusiveMinimum?: number;

    /**
     * Exclusive maximum value.
     *
     * The value must be strictly less than this number.
     */
    exclusiveMaximum?: number;

    /**
     * Value must be divisible by this number.
     *
     * Useful for decimal precision constraints like "two decimal places"
     * (multipleOf: 0.01) or currency amounts (multipleOf: 0.01).
     */
    multipleOf?: number & tags.ExclusiveMinimum<0>;
  }

  /**
   * String type schema.
   *
   * Represents a JSON Schema string type with format validation, pattern
   * matching, and length constraints. Maps to TypeScript `string` type with
   * optional semantic format annotations.
   *
   * @evidence contracts/common.md#principled-implementation It lists optional enum, default, format, pattern, content media type and unsigned length bounds; the format is a union of known names or any other string, which allows custom formats while keeping completion for the known ones.
   * @evidence contracts/common.md#clear-and-simple-design One interface for all string constraints.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts Length bounds are typed with tags and not enforced in this declaration.
   * @evidence contracts/common.md#meaningful-documentation Each member is documented, with a caution that LLMs handle complex patterns poorly.
   */
  export interface IString extends IJsonSchemaAttribute.IString {
    /**
     * Allowed string values.
     *
     * Restricts the value to specific string literals. Maps directly to
     * TypeScript string literal union types.
     */
    enum?: Array<string>;

    /**
     * Default value when not provided.
     *
     * The string to use when the LLM omits this parameter.
     */
    default?: string;

    /**
     * Semantic format specifier.
     *
     * Indicates the string represents a specific format like email, UUID, or
     * date-time. LLMs may use this to generate appropriate values. Common
     * formats include "email", "uri", "uuid", "date-time".
     */
    format?:
      | "binary"
      | "byte"
      | "password"
      | "regex"
      | "uuid"
      | "email"
      | "hostname"
      | "idn-email"
      | "idn-hostname"
      | "iri"
      | "iri-reference"
      | "ipv4"
      | "ipv6"
      | "uri"
      | "uri-reference"
      | "uri-template"
      | "url"
      | "date-time"
      | "date"
      | "time"
      | "duration"
      | "json-pointer"
      | "relative-json-pointer"
      | (string & {});

    /**
     * Regular expression pattern for validation.
     *
     * The string must match this regex pattern. Note that LLMs may struggle
     * with complex regex patterns; simple patterns work best.
     */
    pattern?: string;

    /**
     * MIME type of the string content.
     *
     * Indicates the content type when the string contains encoded binary data,
     * such as "application/json" or "image/png".
     */
    contentMediaType?: string;

    /**
     * Minimum string length.
     *
     * The string must have at least this many characters.
     */
    minLength?: number & tags.Type<"uint64">;

    /**
     * Maximum string length.
     *
     * The string must have at most this many characters.
     */
    maxLength?: number & tags.Type<"uint64">;
  }

  /**
   * Array type schema.
   *
   * Represents a JSON Schema array type with item type validation and size
   * constraints. Maps to TypeScript `T[]` or `Array<T>` types. Note: Tuple
   * types are not supported by LLM schemas.
   *
   * @evidence contracts/common.md#principled-implementation The array has a required `items` schema, optional uniqueness and unsigned size bounds; heterogeneous elements are expressed with anyOf, and tuples are not representable.
   * @evidence contracts/common.md#clear-and-simple-design Four members, with the item schema recursive through the union.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts A plain data record.
   * @evidence contracts/common.md#meaningful-documentation The comment says tuples are unsupported and each member describes its constraint.
   */
  export interface IArray extends IJsonSchemaAttribute.IArray {
    /**
     * Schema for array elements.
     *
     * All elements in the array must conform to this schema. For heterogeneous
     * arrays, use an `anyOf` schema.
     */
    items: ILlmSchema;

    /**
     * Whether elements must be unique.
     *
     * When `true`, no two elements may be equal. Maps to TypeScript `Set<T>`
     * semantics but represented as an array.
     */
    uniqueItems?: boolean;

    /**
     * Minimum number of elements.
     *
     * The array must contain at least this many items.
     */
    minItems?: number & tags.Type<"uint64">;

    /**
     * Maximum number of elements.
     *
     * The array must contain at most this many items.
     */
    maxItems?: number & tags.Type<"uint64">;
  }

  /**
   * Object type schema.
   *
   * Represents a JSON Schema object type with named properties. Maps to
   * TypeScript interface or object type. Supports required property
   * declarations and dynamic additional properties.
   *
   * @evidence contracts/common.md#principled-implementation It has required `properties` and `required`, which the generator always writes even when empty, and an optional additionalProperties that is boolean or a schema; strict mode forces it false.
   * @evidence contracts/common.md#clear-and-simple-design Three members expressing JSON Schema object semantics directly.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts A plain data record.
   * @evidence contracts/common.md#meaningful-documentation The comment and member comments explain defaults, strictness and always-present fields.
   */
  export interface IObject extends IJsonSchemaAttribute.IObject {
    /**
     * Property name to schema mapping.
     *
     * Defines the type of each named property on the object. All properties are
     * defined here regardless of whether they are required or optional.
     * Generated LLM object schemas always include this field, even when it is
     * empty.
     */
    properties: Record<string, ILlmSchema>;

    /**
     * Schema for dynamic/additional properties.
     *
     * - `false` (default): No additional properties allowed
     * - `true`: Any additional properties allowed
     * - Schema: Additional properties must match this schema
     *
     * {@link ILlmSchema.IConfig.strict} forces this to `false`.
     */
    additionalProperties?: ILlmSchema | boolean;

    /**
     * List of required property names.
     *
     * Properties in this array must be present in the object. Generated LLM
     * object schemas always include this field, even when it is empty. In
     * strict mode, all properties become required automatically.
     */
    required: string[];
  }

  /**
   * Reference to a named schema definition.
   *
   * Points to a schema defined in the `$defs` map using a JSON pointer. Used to
   * avoid schema duplication and enable recursive type definitions. The
   * reference path format is `#/$defs/TypeName`, where `TypeName` is one RFC
   * 6901 token encoded as a URI fragment.
   *
   * @evidence contracts/common.md#principled-implementation A reference is a `$ref` string pointing to the `$defs` map in the form `#/$defs/Name`, extending only the attribute record, so the reference carries documentation but no structural keywords.
   * @evidence contracts/common.md#clear-and-simple-design One field added to the attribute record.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts The pointer string is not parsed or resolved by the type.
   * @evidence contracts/common.md#meaningful-documentation The comment explains the pointer format and encoding of the type name.
   */
  export interface IReference extends IJsonSchemaAttribute {
    /**
     * JSON pointer to the referenced schema.
     *
     * Must be in the format `#/$defs/TypeName`, where `TypeName` decodes to a
     * key in the parent schema's `$defs` map.
     */
    $ref: string;
  }

  /**
   * Union type schema (A | B | C).
   *
   * Represents a TypeScript union type where the value can match any one of the
   * member schemas. Use discriminated unions with `x-discriminator` when
   * possible for better LLM comprehension.
   *
   * @evidence contracts/common.md#principled-implementation Union members are in `anyOf`, whose element type excludes nested anyOf so unions are flattened, with an optional discriminator that names the property and maps values to references.
   * @evidence contracts/common.md#clear-and-simple-design Two members and a nested discriminator type in the namespace.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts Flattening is enforced by the type and not by a runtime step here.
   * @evidence contracts/common.md#meaningful-documentation The comment advises discriminated unions and each member says what it holds.
   */
  export interface IAnyOf extends IJsonSchemaAttribute {
    /**
     * Array of possible schemas.
     *
     * The value must match at least one of these schemas. Nested `anyOf`
     * schemas are flattened to avoid deep nesting.
     */
    anyOf: Exclude<ILlmSchema, ILlmSchema.IAnyOf>[];

    /**
     * Discriminator for tagged/discriminated unions.
     *
     * Helps LLMs understand which variant to select based on a discriminating
     * property value. Improves type inference accuracy.
     */
    "x-discriminator"?: IAnyOf.IDiscriminator;
  }
  export namespace IAnyOf {
    /**
     * Discriminator configuration for tagged unions.
     *
     * Specifies which property distinguishes between union variants and maps
     * discriminator values to their corresponding schemas.
     *
     * @evidence contracts/common.md#principled-implementation A property name plus an optional map from literal values to `$ref` strings describes how to select the variant of a tagged union.
     * @evidence contracts/common.md#clear-and-simple-design Two members, with the mapping optional because the value may be inferred.
     * @evidence contracts/common.md#prohibited-implementation-shortcuts The type only describes the discriminator and does not check that members share the property.
     * @evidence contracts/common.md#meaningful-documentation The comment says what the property and mapping are and the requirement for unique literals.
     */
    export interface IDiscriminator {
      /**
       * Name of the discriminating property.
       *
       * This property must exist on all union member object schemas and contain
       * unique literal values that identify each variant.
       */
      propertyName: string;

      /**
       * Mapping from discriminator values to schema references.
       *
       * Keys are the literal values of the discriminator property, values are
       * `$ref` paths to the corresponding schemas.
       */
      mapping?: Record<string, string>;
    }
  }

  /**
   * Null type schema.
   *
   * Represents the JSON null value. In TypeScript union types like `T | null`,
   * this schema appears in an `anyOf` alongside the T schema.
   *
   * @evidence contracts/common.md#principled-implementation The null variant inherits the null attribute record, whose literal "null" type identifies the JSON null value; a nullable type appears as an anyOf containing it.
   * @evidence contracts/common.md#clear-and-simple-design An empty extension.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts It adds no members.
   * @evidence contracts/common.md#meaningful-documentation The comment states how nullable unions use it.
   */
  export interface INull extends IJsonSchemaAttribute.INull {}

  /**
   * Unknown/any type schema.
   *
   * Represents TypeScript `any` or `unknown` types where no specific type
   * constraint is defined. Use sparingly as LLMs may generate unexpected values
   * for unconstrained types.
   *
   * @evidence contracts/common.md#principled-implementation The unknown variant inherits the attribute record with no type, so it represents a value without constraint.
   * @evidence contracts/common.md#clear-and-simple-design An empty extension.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts It adds no members.
   * @evidence contracts/common.md#meaningful-documentation The comment says it stands for any or unknown and warns of its looseness.
   */
  export interface IUnknown extends IJsonSchemaAttribute.IUnknown {}
}
