import { OpenApi } from "@typia/interface";
import { ILlmSchema } from "@typia/interface";
import { TestEquality } from "@typia/oracle/equality";
import { LlmSchemaConverter } from "@typia/utils";

/**
 * Verifies direct inversion preserves each supported constraint-bearing kind.
 *
 * An inverter must preserve non-strict constraint keywords while translating
 * nested LLM schemas to OpenAPI. An integer fixture repeated under a number
 * label cannot distinguish the numeric kind.
 *
 * 1. Invert independently authored string, integer, number, array and object
 *    schemas with the original constraints.
 * 2. Retain each original constraint comparison and add strict descriptor
 *    restoration with an ordinary-prose control.
 *
 * @evidence contracts/testing.md#behavioral-verification LlmSchemaConverter.invert retains the original five comparison names and helper, exercising string metadata, numeric bounds/defaults, unique arrays and nested pattern items. The number fixture now uses the non-integer number kind; strict tags must restore constraints and default mode must retain literal tag-looking prose.
 * @evidence contracts/testing.md#independent-expectations Each input schema is an authored literal whose non-strict keywords must survive by the public conversion contract; it is never generated by the inverter or compiler. Existing comparisons intentionally ignore description, so separate strict/default controls assert exact descriptor behavior.
 * @evidence contracts/testing.md#distinguishing-cases String/integer/number/array/object kinds retain original constraint distinctions. The old number fixture duplicated int32; the corrected number input covers its distinct kind. Strict/default descriptor controls distinguish interpretation from literal prose.
 * @evidence contracts/testing.md#execution-ownership test-utils-unit start explicitly registers this matching export through node:test with the plugin-free oracle/configuration. Inline OpenAPI or LLM fixtures establish portable input meaning independently; the original assertion names remain, and local private helpers are reviewed through this owning case. Native JSON/LLM emission and JSDoc extraction remain in their existing schema/spec batches.
 */
export const test_llm_schema_invert = (): void => {
  const validate = (title: string, schema: ILlmSchema): void => {
    const inverted: OpenApi.IJsonSchema = LlmSchemaConverter.invert({
      components: {},
      $defs: {},
      schema,
    });
    TestEquality.equals(
      title,
      schema,
      inverted as any,
      (key) => key === "description",
    );
  };

  validate("string", {
    type: "string",
    format: "uri",
    contentMediaType: "image/*",
    minLength: 0,
    maxLength: 128,
  });
  validate("integer", {
    type: "integer",
    exclusiveMinimum: 0,
    exclusiveMaximum: 100,
    multipleOf: 5,
    default: 5,
  });
  validate("number", {
    type: "number",
    exclusiveMinimum: 0,
    exclusiveMaximum: 100,
    multipleOf: 5,
    default: 5,
  });

  validate("array", {
    type: "array",
    items: {
      type: "string",
      pattern: "*",
    },
    uniqueItems: true,
  });
  validate("object", {
    type: "object",
    properties: {
      array: {
        type: "array",
        items: {
          type: "string",
          pattern: "*",
        },
        description:
          "List of items.\n\nList of items containing any string values.",
      },
    },
    required: ["array"],
  });

  const described: ILlmSchema = {
    type: "number",
    description: "Numeric amount.\n\n@minimum 2\n@default 3",
  };
  const strict = LlmSchemaConverter.invert({
    config: { strict: true },
    components: {},
    $defs: {},
    schema: described,
  });
  TestEquality.equals(
    "strict descriptor constraints",
    JSON.parse(JSON.stringify(strict)),
    { type: "number", description: "Numeric amount.", minimum: 2, default: 3 },
  );
  const ordinary = LlmSchemaConverter.invert({
    config: { strict: false },
    components: {},
    $defs: {},
    schema: described,
  });
  TestEquality.equals(
    "ordinary descriptor remains prose",
    JSON.parse(JSON.stringify(ordinary)),
    {
      type: "number",
      description: "Numeric amount.\n\n@minimum 2\n@default 3",
    },
  );
};
