import { OpenApi, SwaggerV2 } from "@typia/interface";
import { OpenApiConverter } from "@typia/utils";
import fs from "fs";
import typia from "typia";

import { TestGlobal } from "../../TestGlobal";

/**
 * Verifies every Swagger 2.0 example upgrades to a valid emended document.
 *
 * Upgrading real documents exercises every conversion branch; the result must
 * satisfy the OpenApi.IDocument declaration.
 *
 * 1. Read each v2.0 example and validate it natively.
 * 2. Upgrade it.
 * 3. Assert the result with the native validator.
 *
 * @evidence contracts/testing.md#behavioral-verification Each example is upgraded and the result checked by a natively generated validator.
 * @evidence contracts/testing.md#independent-expectations The OpenApi.IDocument declaration is the specification and the validator is generated independently of the converter.
 * @evidence contracts/testing.md#distinguishing-cases Every example is a case with structural validity only.
 * @evidence contracts/testing.md#execution-ownership The test-utils test:integration command (DynamicExecutor over src/features under ttsx with the native typia plugin) discovers this exported case. typia.assert validators are generated by the native transform and the examples are read from disk.
 */
export const test_document_upgrade_v20 = async (): Promise<void> => {
  const path: string = `${TestGlobal.ROOT}/examples/v2.0`;
  for (const file of await fs.promises.readdir(path)) {
    if (file.endsWith(".json") === false) continue;
    const swagger: SwaggerV2.IDocument = typia.assert<SwaggerV2.IDocument>(
      JSON.parse(await fs.promises.readFile(`${path}/${file}`, "utf8")),
    );
    const openapi: OpenApi.IDocument =
      OpenApiConverter.upgradeDocument(swagger);
    typia.assert(openapi);
  }
};
