import { OpenApi } from "@typia/interface";
import { TestEquality } from "@typia/template/equality";
import { OpenApiValidator } from "@typia/utils";
import typia from "typia";

interface IUndefined {
  name: string;
  nothing: undefined;
  grade: number | undefined;
}

/**
 * Verifies `equals: true` agrees with `typia.equals` on `undefined` values.
 *
 * A key whose value is `undefined` has no JSON form — `JSON.stringify` erases
 * it — so the value does not carry it as a property and it cannot be
 * superfluous. The closure check walked `Object.entries` and reported it
 * anyway, so a value typia generates was rejected against the schema typia
 * emits from the same type. `equals` mode exists to mirror `typia.equals`, and
 * `typia.equals` is an independent code generator, which makes it the oracle
 * here rather than the validator's own output.
 *
 * Both branches that walk `Object.entries` must agree on this: the closure
 * check, and the one constraining extras against an `additionalProperties`
 * schema, which would otherwise validate the key as a required value.
 *
 * 1. Confirm an `undefined`-valued key is not superfluous under `equals: true`,
 *    and that a defined extra key still is.
 * 2. Confirm an `additionalProperties` schema does not constrain a key with no
 *    JSON form, under either `equals` value.
 * 3. Round-trip a type whose members erase from the emitted schema and require the
 *    emitter's own schema to accept the emitter's own value.
 *
 * @evidence contracts/testing.md#behavioral-verification OpenApiValidator in equals mode is run on objects with undefined-valued keys and must agree with the natively generated typia.equals on the same values.
 * @evidence contracts/testing.md#independent-expectations typia.equals is an independent code generator and is the oracle; the values are authored.
 * @evidence contracts/testing.md#distinguishing-cases The closure check and the additionalProperties branch both walk entries, and each is asserted with undefined-valued keys.
 * @evidence contracts/testing.md#execution-ownership The test-utils test:integration command (DynamicExecutor over src/features under ttsx with the native typia plugin) discovers this exported case. typia.equals is generated by the native transform; the OpenAPI validator runs in process.
 * @evidence contracts/e2e.md#necessary-boundary Native equals and schemas for undefined-only members reach OpenApiValidator. Missing/present/unknown-member verdicts and erased-member comparisons distinguish projection interoperability; handwritten object rows retain portable rule assertions.
 * @evidence contracts/e2e.md#shared-execution This case shares the test-utils integration project and native-plugin artifact lifecycle with the other src/features exports. Its runtime rows reuse emitted schemas/callbacks in this invocation instead of starting a compiler host per input; it performs no independent installation or host launch.
 * @evidence contracts/e2e.md#state-isolation-and-reuse-validity Each invocation owns its schema/definition objects and payloads; document callers parse fresh text before conversion. Compiler-artifact reuse cannot supply a prior runtime verdict. This case opens no persistent service/process handle; fixture-reader unit temporary files are owned and released by that separate unit.
 * @evidence contracts/e2e.md#preserved-coverage The previous inputs, producer calls and behavioral assertions remain in this exported DynamicExecutor case; portable rows described above have not yet been transferred to unit coverage. Producer parity and structural acceptance retain their stated oracle limits rather than certifying semantic correctness.
 */
export const test_openapi_validator_object_undefined_property = (): void => {
  const schema: OpenApi.IJsonSchema.IObject = {
    type: "object",
    properties: { a: { type: "string" } },
    required: ["a"],
    additionalProperties: false,
  };
  const accepts = (value: unknown): boolean =>
    OpenApiValidator.validate({
      components: {},
      schema,
      value,
      required: true,
      equals: true,
    }).success;

  TestEquality.equals(
    "an undefined-valued key is not a property",
    accepts({ a: "value", b: undefined }),
    true,
  );
  TestEquality.equals(
    "a defined extra key is still superfluous",
    accepts({ a: "value", b: 1 }),
    false,
  );
  TestEquality.equals(
    "an undefined-valued key does not excuse its siblings",
    accepts({ a: "value", b: undefined, c: 1 }),
    false,
  );

  // `typia.equals` is the oracle, and it accepts what the closure check used to
  // reject.
  TestEquality.equals(
    "typia.equals accepts an undefined-valued key",
    typia.equals<{ a: string }>({ a: "value", b: undefined }),
    true,
  );
  TestEquality.equals(
    "typia.equals rejects a defined extra key",
    typia.equals<{ a: string }>({ a: "value", b: 1 }),
    false,
  );

  // The sibling branch: an `additionalProperties` schema constrains the extra
  // values, but a key with no JSON form is not one of them. `typia` accepts it
  // on an index-signature type under both `is` and `equals`.
  const constrained: OpenApi.IJsonSchema.IObject = {
    type: "object",
    properties: { a: { type: "string" } },
    required: ["a"],
    additionalProperties: { type: "string" },
  };
  const constrains = (value: unknown, equals: boolean): boolean =>
    OpenApiValidator.validate({
      components: {},
      schema: constrained,
      value,
      required: true,
      equals,
    }).success;
  for (const equals of [false, true]) {
    TestEquality.equals(
      `equals: ${equals} - a constrained object ignores an undefined-valued key`,
      constrains({ a: "value", b: undefined }, equals),
      true,
    );
    TestEquality.equals(
      `equals: ${equals} - a constrained object still checks a defined extra key`,
      constrains({ a: "value", b: 1 }, equals),
      false,
    );
  }
  TestEquality.equals(
    "typia accepts an undefined-valued key on an index-signature type",
    typia.equals<{ a: string; [key: string]: string }>({
      a: "value",
      b: undefined,
    } as any),
    true,
  );

  // The emitter's own round trip. `nothing` and an `undefined` union member
  // have no JSON form, so typia erases them from the schema while the value
  // still spells the keys out.
  const collection = typia.json.schema<IUndefined>();
  const value: IUndefined = {
    name: "someone",
    nothing: undefined,
    grade: undefined,
  };
  TestEquality.equals(
    "typia.equals accepts its own erased-member value",
    typia.equals<IUndefined>(value),
    true,
  );
  TestEquality.equals(
    "the emitted schema accepts its own erased-member value",
    OpenApiValidator.validate({
      components: collection.components,
      schema: collection.schema,
      value,
      required: true,
      equals: true,
    }).success,
    true,
  );
  TestEquality.equals(
    "the emitted schema still rejects a stray property",
    OpenApiValidator.validate({
      components: collection.components,
      schema: collection.schema,
      value: { ...value, stray: "extra" },
      required: true,
      equals: true,
    }).success,
    false,
  );
};
