import { TestEquality } from "@typia/template/equality";
import { OpenApiValidator } from "@typia/utils";
import typia from "typia";

interface IUndefined {
  name: string;
  nothing: undefined;
  grade: number | undefined;
}

/**
 * Verifies `equals: true` agrees with `typia.equals` on `undefined` values.
 *
 * A key whose value is `undefined` has no JSON form — `JSON.stringify` erases
 * it — so the value does not carry it as a property and it cannot be
 * superfluous. The closure check walked `Object.entries` and reported it
 * anyway, so a value typia generates was rejected against the schema typia
 * emits from the same type. `equals` mode exists to mirror `typia.equals`, and
 * `typia.equals` is an independent code generator, which makes it the oracle
 * here rather than the validator's own output.
 *
 * Both branches that walk `Object.entries` must agree on this: the closure
 * check, and the one constraining extras against an `additionalProperties`
 * schema, which would otherwise validate the key as a required value.
 *
 * 1. Confirm generated equals accepts an undefined extra and rejects a defined
 *    extra.
 * 2. Confirm generated equals accepts an undefined index-signature value.
 * 3. Round-trip a type whose members erase from the emitted schema and require the
 *    emitter's own schema to accept the emitter's own value.
 *
 * @evidence contracts/testing.md#behavioral-verification Generated typia.equals callbacks check authored undefined and defined extras; OpenApiValidator checks the emitted erased-member schema against an accepted value and a defined stray-property control.
 * @evidence contracts/testing.md#independent-expectations The payloads and six literal verdicts are authored independently; generated equals and schema validation are complementary projection checks, while handwritten rule coverage belongs to the portable peer.
 * @evidence contracts/testing.md#distinguishing-cases Generated closed-object and index-signature callbacks distinguish undefined from defined extras; emitted erased-member schema acceptance has a defined-stray rejection control. The portable peer retains closure and constrained-extra literal rows under both equals settings.
 * @evidence contracts/testing.md#execution-ownership The test-utils test:integration command (DynamicExecutor over src/features under ttsx with the native typia plugin) discovers this exported case. typia.equals is generated by the native transform; the OpenAPI validator runs in process.
 * @evidence contracts/e2e.md#necessary-boundary Native equals and schemas for undefined-only members reach OpenApiValidator. Missing/present/unknown-member verdicts and erased-member comparisons distinguish projection interoperability; the seven handwritten rule assertions live in the object_undefined_property_portable unit peer.
 * @evidence contracts/e2e.md#shared-execution This case shares the test-utils integration project and native-plugin artifact lifecycle with the other src/features exports. Its runtime rows reuse emitted schemas/callbacks in this invocation instead of starting a compiler host per input; it performs no independent installation or host launch.
 * @evidence contracts/e2e.md#state-isolation-and-reuse-validity Each invocation owns its schema/definition objects and payloads; document callers parse fresh text before conversion. Compiler-artifact reuse cannot supply a prior runtime verdict. This case opens no persistent service/process handle; fixture-reader unit temporary files are owned and released by that separate unit.
 * @evidence contracts/e2e.md#preserved-coverage The original native inputs, producer calls and six native behavioral assertions remain here; seven original handwritten rule assertions move unchanged to the registered object_undefined_property_portable unit peer. Producer parity and structural acceptance retain their stated oracle limits rather than certifying semantic correctness.
 */
export const test_openapi_validator_object_undefined_property = (): void => {
  // `typia.equals` is the oracle, and it accepts what the closure check used to
  // reject.
  TestEquality.equals(
    "typia.equals accepts an undefined-valued key",
    typia.equals<{ a: string }>({ a: "value", b: undefined }),
    true,
  );
  TestEquality.equals(
    "typia.equals rejects a defined extra key",
    typia.equals<{ a: string }>({ a: "value", b: 1 }),
    false,
  );

  // The sibling branch: an `additionalProperties` schema constrains the extra
  // values, but a key with no JSON form is not one of them. `typia` accepts it
  // on an index-signature type under `equals`.
  TestEquality.equals(
    "typia accepts an undefined-valued key on an index-signature type",
    typia.equals<{ a: string; [key: string]: string }>({
      a: "value",
      b: undefined,
    } as any),
    true,
  );

  // The emitter's own round trip. `nothing` and an `undefined` union member
  // have no JSON form, so typia erases them from the schema while the value
  // still spells the keys out.
  const collection = typia.json.schema<IUndefined>();
  const value: IUndefined = {
    name: "someone",
    nothing: undefined,
    grade: undefined,
  };
  TestEquality.equals(
    "typia.equals accepts its own erased-member value",
    typia.equals<IUndefined>(value),
    true,
  );
  TestEquality.equals(
    "the emitted schema accepts its own erased-member value",
    OpenApiValidator.validate({
      components: collection.components,
      schema: collection.schema,
      value,
      required: true,
      equals: true,
    }).success,
    true,
  );
  TestEquality.equals(
    "the emitted schema still rejects a stray property",
    OpenApiValidator.validate({
      components: collection.components,
      schema: collection.schema,
      value: { ...value, stray: "extra" },
      required: true,
      equals: true,
    }).success,
    false,
  );
};
