
// Code generated by packages/ttsc/tools/gen_shims. DO NOT EDIT.

package core

import "context"
import "github.com/microsoft/typescript-go/internal/core"
import "iter"
import _ "unsafe"

//go:linkname ApplyBulkEdits github.com/microsoft/typescript-go/internal/core.ApplyBulkEdits
func ApplyBulkEdits(text string, edits []core.TextChange) string
type Arena[T any] = core.Arena[T]
//go:linkname BoolToTristate github.com/microsoft/typescript-go/internal/core.BoolToTristate
func BoolToTristate(b bool) core.Tristate
type BreadthFirstSearchLevel[K comparable, N any] = core.BreadthFirstSearchLevel[K,N]
type BreadthFirstSearchOptions[K comparable, N any] = core.BreadthFirstSearchOptions[K,N]
type BreadthFirstSearchResult[N any] = core.BreadthFirstSearchResult[N]
type BuildOptions = core.BuildOptions
//go:linkname CompareBooleans github.com/microsoft/typescript-go/internal/core.CompareBooleans
func CompareBooleans(a bool, b bool) int
//go:linkname CompareTextRanges github.com/microsoft/typescript-go/internal/core.CompareTextRanges
func CompareTextRanges(r1 core.TextRange, r2 core.TextRange) int
type CompilerOptions = core.CompilerOptions
//go:linkname ComputeECMALineStarts github.com/microsoft/typescript-go/internal/core.ComputeECMALineStarts
func ComputeECMALineStarts(text string) core.ECMALineStarts
//go:linkname ComputeECMALineStartsSeq github.com/microsoft/typescript-go/internal/core.ComputeECMALineStartsSeq
func ComputeECMALineStartsSeq(text string) iter.Seq[core.TextPos]
type ECMALineStarts = core.ECMALineStarts
var EmptyCompilerOptions = core.EmptyCompilerOptions
var ExclusivelyPrefixedNodeCoreModules = core.ExclusivelyPrefixedNodeCoreModules
//go:linkname GetNewLineKind github.com/microsoft/typescript-go/internal/core.GetNewLineKind
func GetNewLineKind(s string) core.NewLineKind
//go:linkname GetRequestID github.com/microsoft/typescript-go/internal/core.GetRequestID
func GetRequestID(ctx context.Context) string
//go:linkname GetScriptKindFromFileName github.com/microsoft/typescript-go/internal/core.GetScriptKindFromFileName
func GetScriptKindFromFileName(fileName string) core.ScriptKind
//go:linkname GetSpellingSuggestionForStrings github.com/microsoft/typescript-go/internal/core.GetSpellingSuggestionForStrings
func GetSpellingSuggestionForStrings(name string, candidates iter.Seq[string]) string
//go:linkname IndexAfter github.com/microsoft/typescript-go/internal/core.IndexAfter
func IndexAfter(s string, pattern string, startIndex int) int
type JsxEmit = core.JsxEmit
const JsxEmitNone = core.JsxEmitNone
const JsxEmitPreserve = core.JsxEmitPreserve
const JsxEmitReact = core.JsxEmitReact
const JsxEmitReactJSX = core.JsxEmitReactJSX
const JsxEmitReactJSXDev = core.JsxEmitReactJSXDev
const JsxEmitReactNative = core.JsxEmitReactNative
type LanguageVariant = core.LanguageVariant
const LanguageVariantJSX = core.LanguageVariantJSX
const LanguageVariantStandard = core.LanguageVariantStandard
type LimitedSemaphore = core.LimitedSemaphore
type LinkStore[K comparable, V any] = core.LinkStore[K,V]
type ModuleDetectionKind = core.ModuleDetectionKind
const ModuleDetectionKindAuto = core.ModuleDetectionKindAuto
const ModuleDetectionKindForce = core.ModuleDetectionKindForce
const ModuleDetectionKindLegacy = core.ModuleDetectionKindLegacy
const ModuleDetectionKindNone = core.ModuleDetectionKindNone
type ModuleKind = core.ModuleKind
const ModuleKindAMD = core.ModuleKindAMD
const ModuleKindCommonJS = core.ModuleKindCommonJS
const ModuleKindES2015 = core.ModuleKindES2015
const ModuleKindES2020 = core.ModuleKindES2020
const ModuleKindES2022 = core.ModuleKindES2022
const ModuleKindESNext = core.ModuleKindESNext
const ModuleKindNode16 = core.ModuleKindNode16
const ModuleKindNode18 = core.ModuleKindNode18
const ModuleKindNode20 = core.ModuleKindNode20
const ModuleKindNodeNext = core.ModuleKindNodeNext
const ModuleKindNone = core.ModuleKindNone
const ModuleKindPreserve = core.ModuleKindPreserve
const ModuleKindSystem = core.ModuleKindSystem
var ModuleKindToModuleResolutionKind = core.ModuleKindToModuleResolutionKind
const ModuleKindUMD = core.ModuleKindUMD
type ModuleResolutionKind = core.ModuleResolutionKind
const ModuleResolutionKindBundler = core.ModuleResolutionKindBundler
const ModuleResolutionKindClassic = core.ModuleResolutionKindClassic
const ModuleResolutionKindNode10 = core.ModuleResolutionKindNode10
const ModuleResolutionKindNode16 = core.ModuleResolutionKindNode16
const ModuleResolutionKindNodeNext = core.ModuleResolutionKindNodeNext
const ModuleResolutionKindUnknown = core.ModuleResolutionKindUnknown
//go:linkname NewLimitedSemaphore github.com/microsoft/typescript-go/internal/core.NewLimitedSemaphore
func NewLimitedSemaphore(maxConcurrency int) *core.LimitedSemaphore
type NewLineKind = core.NewLineKind
const NewLineKindCRLF = core.NewLineKindCRLF
const NewLineKindLF = core.NewLineKindLF
const NewLineKindNone = core.NewLineKindNone
//go:linkname NewTextRange github.com/microsoft/typescript-go/internal/core.NewTextRange
func NewTextRange(pos int, end int) core.TextRange
//go:linkname NewThrottleGroup github.com/microsoft/typescript-go/internal/core.NewThrottleGroup
func NewThrottleGroup(ctx context.Context, semaphore chan struct{}) *core.ThrottleGroup
//go:linkname NewWorkGroup github.com/microsoft/typescript-go/internal/core.NewWorkGroup
func NewWorkGroup(singleThreaded bool) core.WorkGroup
var NodeCoreModules = core.NodeCoreModules
//go:linkname NonRelativeModuleNameForTypingCache github.com/microsoft/typescript-go/internal/core.NonRelativeModuleNameForTypingCache
func NonRelativeModuleNameForTypingCache(moduleName string) string
type ParsedOptions = core.ParsedOptions
type Pattern = core.Pattern
type PollingKind = core.PollingKind
const PollingKindDynamicPriority = core.PollingKindDynamicPriority
const PollingKindFixedChunkSize = core.PollingKindFixedChunkSize
const PollingKindFixedInterval = core.PollingKindFixedInterval
const PollingKindNone = core.PollingKindNone
const PollingKindPriorityInterval = core.PollingKindPriorityInterval
//go:linkname PositionToLineAndByteOffset github.com/microsoft/typescript-go/internal/core.PositionToLineAndByteOffset
func PositionToLineAndByteOffset(position int, lineStarts []core.TextPos) (line int, byteOffset int)
type ProjectReference = core.ProjectReference
type ResolutionMode = core.ResolutionMode
const ResolutionModeCommonJS = core.ResolutionModeCommonJS
const ResolutionModeESM = core.ResolutionModeESM
const ResolutionModeNone = core.ResolutionModeNone
//go:linkname ResolveConfigFileNameOfProjectReference github.com/microsoft/typescript-go/internal/core.ResolveConfigFileNameOfProjectReference
func ResolveConfigFileNameOfProjectReference(path string) string
//go:linkname ResolveProjectReferencePath github.com/microsoft/typescript-go/internal/core.ResolveProjectReferencePath
func ResolveProjectReferencePath(ref *core.ProjectReference) string
type ScriptKind = core.ScriptKind
const ScriptKindDeferred = core.ScriptKindDeferred
const ScriptKindExternal = core.ScriptKindExternal
const ScriptKindJS = core.ScriptKindJS
const ScriptKindJSON = core.ScriptKindJSON
const ScriptKindJSX = core.ScriptKindJSX
const ScriptKindTS = core.ScriptKindTS
const ScriptKindTSX = core.ScriptKindTSX
const ScriptKindUnknown = core.ScriptKindUnknown
type ScriptTarget = core.ScriptTarget
const ScriptTargetES2015 = core.ScriptTargetES2015
const ScriptTargetES2016 = core.ScriptTargetES2016
const ScriptTargetES2017 = core.ScriptTargetES2017
const ScriptTargetES2018 = core.ScriptTargetES2018
const ScriptTargetES2019 = core.ScriptTargetES2019
const ScriptTargetES2020 = core.ScriptTargetES2020
const ScriptTargetES2021 = core.ScriptTargetES2021
const ScriptTargetES2022 = core.ScriptTargetES2022
const ScriptTargetES2023 = core.ScriptTargetES2023
const ScriptTargetES2024 = core.ScriptTargetES2024
const ScriptTargetES2025 = core.ScriptTargetES2025
const ScriptTargetES5 = core.ScriptTargetES5
const ScriptTargetESNext = core.ScriptTargetESNext
const ScriptTargetJSON = core.ScriptTargetJSON
const ScriptTargetLatest = core.ScriptTargetLatest
const ScriptTargetLatestStandard = core.ScriptTargetLatestStandard
const ScriptTargetNone = core.ScriptTargetNone
type Semaphore = core.Semaphore
//go:linkname ShouldRewriteModuleSpecifier github.com/microsoft/typescript-go/internal/core.ShouldRewriteModuleSpecifier
func ShouldRewriteModuleSpecifier(specifier string, compilerOptions *core.CompilerOptions) bool
type Stack[T any] = core.Stack[T]
//go:linkname StringifyJson github.com/microsoft/typescript-go/internal/core.StringifyJson
func StringifyJson(input any, prefix string, indent string) (string, error)
const TSFalse = core.TSFalse
const TSTrue = core.TSTrue
const TSUnknown = core.TSUnknown
type TextChange = core.TextChange
type TextPos = core.TextPos
type TextRange = core.TextRange
type ThrottleGroup = core.ThrottleGroup
type Tristate = core.Tristate
//go:linkname TryParsePattern github.com/microsoft/typescript-go/internal/core.TryParsePattern
func TryParsePattern(pattern string) core.Pattern
type TypeAcquisition = core.TypeAcquisition
//go:linkname UTF16Len github.com/microsoft/typescript-go/internal/core.UTF16Len
func UTF16Len(s string) core.UTF16Offset
type UTF16Offset = core.UTF16Offset
//go:linkname UndefinedTextRange github.com/microsoft/typescript-go/internal/core.UndefinedTextRange
func UndefinedTextRange() core.TextRange
type UnlimitedSemaphore = core.UnlimitedSemaphore
var UnprefixedNodeCoreModules = core.UnprefixedNodeCoreModules
//go:linkname Version github.com/microsoft/typescript-go/internal/core.Version
func Version() string
//go:linkname VersionMajorMinor github.com/microsoft/typescript-go/internal/core.VersionMajorMinor
func VersionMajorMinor() string
type WatchDirectoryKind = core.WatchDirectoryKind
const WatchDirectoryKindDynamicPriorityPolling = core.WatchDirectoryKindDynamicPriorityPolling
const WatchDirectoryKindFixedChunkSizePolling = core.WatchDirectoryKindFixedChunkSizePolling
const WatchDirectoryKindFixedPollingInterval = core.WatchDirectoryKindFixedPollingInterval
const WatchDirectoryKindNone = core.WatchDirectoryKindNone
const WatchDirectoryKindUseFsEvents = core.WatchDirectoryKindUseFsEvents
type WatchFileKind = core.WatchFileKind
const WatchFileKindDynamicPriorityPolling = core.WatchFileKindDynamicPriorityPolling
const WatchFileKindFixedChunkSizePolling = core.WatchFileKindFixedChunkSizePolling
const WatchFileKindFixedPollingInterval = core.WatchFileKindFixedPollingInterval
const WatchFileKindNone = core.WatchFileKindNone
const WatchFileKindPriorityPollingInterval = core.WatchFileKindPriorityPollingInterval
const WatchFileKindUseFsEvents = core.WatchFileKindUseFsEvents
const WatchFileKindUseFsEventsOnParentDirectory = core.WatchFileKindUseFsEventsOnParentDirectory
type WatchOptions = core.WatchOptions
//go:linkname WithRequestID github.com/microsoft/typescript-go/internal/core.WithRequestID
func WithRequestID(ctx context.Context, id string) context.Context
type WorkGroup = core.WorkGroup
